### ISSUE TITLE
mouse_callback on WiFi widget no effect

### ISSUE THREAD

**Issue by mrchainman** [elParaguayo/qtile-extras#101]
Hi, I am using your WiFi Widget, I added a mousecallback for button3, but nothing happens when I click it. 
Expanding it with Button 1 works.
Nothing in the logs exept:

2022-09-08 09:52:54,405 DEBUG libqtile core.py:_xpoll():L301 X11 event: ButtonPress (targets: 2)
2022-09-08 09:52:54,539 DEBUG libqtile core.py:_xpoll():L301 X11 event: ButtonRelease (targets: 2)
2022-09-08 09:52:55,735 DEBUG libqtile core.py:_xpoll():L301 X11 event: ButtonPress (targets: 2)
2022-09-08 09:52:55,869 DEBUG libqtile core.py:_xpoll():L301 X11 event: ButtonRelease (targets: 2)

Here is the relevant config:

def open_wifi():
    qtile.cmd_spawn("iwgtk")

...

w_wlan = (
        widget.WiFiIcon(
            active_colour=colors[11],
            inactive_colour=colors[16],
            background=colors[12],
            foreground=colors[11],
            font="JetBrainsMono Nerd Font",
            # disconnected_message="󰖪",
            fontsize=12,
            interface="wlan0",
            update_interval=5,
            mouse_callbacks={"Button3": open_wifi},
            padding=8,
            decorations=_left_decor(colors[19]),
        ),
        separator(),
)

**Comment by elParaguayo** [comment]
Thanks for the report.

Yes, it's a bug. I can see the error in the code. Will fix when I get a chance.

**Comment by mrchainman** [comment]
Awesome response time! thanks :D

**Comment by elParaguayo** [comment]
> Awesome response time! thanks :D

You caught me at a good time. Fix might take a bit longer...

**Comment by mrchainman** [comment]
No worries, just thought I report since i didn't know if it was a Bug or an issue with my config.

**Comment by mrchainman** [comment]
That was quick,  will test it and report back :)

**Comment by mrchainman** [comment]
Nice, works perfectly now! :)

**Comment by elParaguayo** [comment]
Cool. Thanks for confirming.

I'm just waiting for a PR to be merged in the main repo (which will stop my tests failing) and then we can get this merged.
