### ISSUE TITLE
[feature request] Specify position on screen for popuptoolkit

### ISSUE THREAD

**Issue by mrchainman** [elParaguayo/qtile-extras#106]
Hi, playing around with the popuptoolkit.
As far as i know, you can only center the window with center=True as a parameter to layout.show
It would be cool to specify also the postition when not centering, I imagine something like this:

layout.show(x=100px,y=500px)
or
layout.show(x=5%,y=10%)

Thanks :)

**Comment by mrchainman** [comment]
Awesome

**Comment by mrchainman** [comment]
Hi, since i need the feature, I started working on it myself. I made a small change, to allow to position x and y. I am not sure tought, where the 0 0 point for the User should be, top left? bottom right?
Here the snippet + an example:
```
diff --git a/qtile_extras/popup/toolkit.py b/qtile_extras/popup/toolkit.py
index 556db83..06b2073 100644
--- a/qtile_extras/popup/toolkit.py
+++ b/qtile_extras/popup/toolkit.py
@@ -172,7 +172,7 @@ class _PopupLayout(configurable.Configurable):
             func = self.queued_draws.pop()
             func()
 
-    def show(self, x=None, y=None, centered=False, warp_pointer=False):
+    def show(self, x=None, y=None, centered=False, warp_pointer=False, pos_x=None, pos_y=None):
         """Display the popup. Can be centered on screen."""
         if not self.configured:
             self._configure()
@@ -182,6 +182,14 @@ class _PopupLayout(configurable.Configurable):
         if y is None:
             y = self.qtile.current_screen.y
 
+        if pos_x:
+            x = (
+                int((self.qtile.current_screen.width - self.popup.width - pos_x))
+                )
+        if pos_y:
+            y = (
+                int((self.qtile.current_screen.height - self.popup.height - pos_y))
+                )
         if centered:
             x = (
                 int((self.qtile.current_screen.width - self.popup.width) / 2)
```

layout.show(pos_x=10, pos_y=700)

![image](https://user-images.githubusercontent.com/59087991/191777755-9a9305aa-ef4b-4428-8ea4-40043df6635f.png)

**Comment by elParaguayo** [comment]
We don't need new X and Y parameters in the command. We just need to handle the existing ones better.

You can already specify X and Y but they are not adjusted for multiple monitors. 0, 0 is top left.

**Comment by mrchainman** [comment]
Alright, thanks for the feedback

**Comment by elParaguayo** [comment]
#160 should fix the positioning of popups so using `popup.show(x=10, y=700)` will place the popup at those coordinates on the current screen.

Would be great if you're able to test.

**Comment by mrchainman** [comment]
Sorry didn't get around till now for testing.
Works as expected.
Thanks for implementing!
