### ISSUE TITLE
Visual anomalies with PowerLineDecoration

### ISSUE THREAD

**Issue by arjan-s** [elParaguayo/qtile-extras#111]
Hi, thank you for the PowerLineDecoration! I love it!

I'd like to report two visual anomalies that are visible on my setup:

1. When using a transparent background on widgets, the PowerLineDecoration doesn't handle this well, the different internal parts of the decoration are visible and overlay each other.

![image-title](http://i.imgur.com/rEhRshd.png)

Used background definitions from left to right:
```
background="88888888",
background="aaaaaa88",
background="88888888",
background="aaaaaa88",
```

2. The StatusNotifier widget (from qtile-extras) doesn't seem to be compatible. To the right side of it, the decoration isn't used but it is just a straight line.

![image-title](http://i.imgur.com/56ShdYU.png)

**Comment by elParaguayo** [comment]
Thanks for the response.

Quick question: is this on X11 or Wayland?

The first one is definitely an issue but that's really weird as I can't immediately see why that would happen. Will need to do some testing.

As for the second, `StatusNotifier` works fine with this decoration (I've tested it). It sounds like you're using the qtile version, rather than the qtile-extras one.

Can you share your config as that will help me look at both of these.

**Comment by arjan-s** [comment]
I'm running on Wayland, and I'm definitely using the qtile-extras StatusNotifier, because I need the context menus of some apps.
I've uploaded my config here: https://gist.github.com/arjan-s/9e5a7eddecb8c7358797ced435869841

**Comment by elParaguayo** [comment]
OK - I've found the bug that causes the first issue. Now need to think of the best way to fix it!

**Comment by elParaguayo** [comment]
Also, confirmed bug with SNI on Wayland. Very odd!

**Comment by arjan-s** [comment]
I'm afraid the PR didn't fix the first issue, sorry:
![image-title](http://i.imgur.com/ufty3uz.png)

**Comment by elParaguayo** [comment]
Really? It's working nicely on mine. Are you sure you're running the patched version?

**Comment by elParaguayo** [comment]
Nope, you're right, not working. Weird.

**Comment by elParaguayo** [comment]
Fixed the StatusNotifier missing arrow. Just need to fix transparency. Will need to wait until tomorrow now.

**Comment by arjan-s** [comment]
Awesome, thank you!
Will test tonight and let you know!

**Comment by arjan-s** [comment]
Yes, both issues are now solved! Thank you!!
