### ISSUE TITLE
widget.StatusNotifier miss a bunch of app

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#112]
widget.StatusNotifier(icon_size=40, icon_theme="oomox-Catppuccin_Mid_Dark"),

In my autostart.sh, i have those apps: 
nm-applet &
blueberry-tray &
volumeicon &
deluge &
discord &

Only discord app is shown by widget.StatusNotifier

Those app properly appear when using widget.Systray

**Comment by elParaguayo** [comment]
An app working on `Systray` does not, unfortunately, mean it will work on `StatusNotifier`. They are two completely different specifications. I would therefore assume those other apps have not implemented the StatustNotifier specification.

**Comment by elParaguayo** [comment]
I'm going to close this for now as I don't believe it's a bug. However, feel free to reopen if you are sure some of those apps should work with StatusNotifier.
