### ISSUE TITLE
widget.CurrentLayoutIcon: icon disappearing with use_mask = True 

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#113]
If use_mask is set to True, the icon disappears.
Playing with foreground color doesn't fix the issue.

widget.CurrentLayoutIcon(scale = 0.66, use_mask = True, foreground=colors[2]),

**Comment by elParaguayo** [comment]
Any error in your log?

**Comment by Crystal4276** [comment]
For the colors [2]: 
`def init_colors():
    return [["#cdd6f4", "#cdd6f4"], # color 0 Blue Catppuccin Mocha
            ["#1e1e2e", "#1e1e2e"], # color 1 Base Catppuccin Mocha
            ["#9399b2", "#9399b2"], # color 2 Overlay 2 Catppuccin Mocha
            ["#f5c2e7", "#f5c2e7"], # color 3 Pink Catppuccin Mocha
            ["00000000", "00000000"], # color 4 Transparent
            ["#f3f4f5", "#f3f4f5"], # color 5 White
            ["#45475a", "#45475a"], # color 6 Surface0 Catppuccin Mocha
            ["#1e1e2ea9", "#1e1e2ea9"], # color 7 Base Catppuccin Mocha 66% transparency
            ["#fab387", "#fab387"], # color 8 Peach Catppuccin Mocha
            ["#313244", "#313244"]] # color 9
colors = init_colors()`
Any color from this list provide the same results.
No foreground parameter specified + use_mask = True has the same results

I purged the qtile.log and restarted qtile.
It's empty.

**Comment by elParaguayo** [comment]
Not sure what to say here. I can't recreate this at all. Using a list of colours works fine for me.

Do you have the latest version of qtile-extras installed? (although, if you didn't, you should just get the standard white icons).

What happens if you hardcode a single `foreground` value?

**Comment by Crystal4276** [comment]
Qtile-extra version :
aur/qtile-extras-git r142.e522e59-1 [+1 ~0.56] [Installed: r152.a89e5b8-1]

widget.CurrentLayoutIcon(scale = 0.66, use_mask = True, foreground="#f5c2e7"),
Same behaviour. 

With:
widget.CurrentLayoutIcon(scale = 0.66, use_mask = False, foreground="#f5c2e7"),
Icon reappears but of course the icon color is still white

Is there any other log i could check to find what's going on ?

**Comment by elParaguayo** [comment]
Is this Wayland or X11?

**Comment by Crystal4276** [comment]
X11 

I have another list of bug for Wayland when i have more courage to write it down

**Comment by elParaguayo** [comment]
Can you try creating a `MaskWidget` from here: https://qtile-extras.readthedocs.io/en/latest/manual/how_to/img-mask.html

You'll need to set a valid icon in the code but I'm interested to see if this works for you.

**Comment by Crystal4276** [comment]
I did try. And it works !
I get three icons, red green and rainbow.

**Comment by elParaguayo** [comment]
Ok. So the image mask does work for you. That's good but now I'm more confused!

I'm away from my computer at the moment but will take a look again at this later.

**Comment by Crystal4276** [comment]
Going from qtile stable version to git version may have some the problem.
Now inputting true for use_mask has the correct behaviour.
