### ISSUE TITLE
Systray icons invisible with updated rectdecoration + systray

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#120]
git version of qtile and qtile-extra
```
qtile-extras-git r142.e522e59-1
qtile-git 0.20.0.r33.gc1f50739-2
```
The systray icons appears behind the rectdecoration or are invisible (between launchbar and clock)
With main bar transparency:
![image](https://user-images.githubusercontent.com/27446196/192159066-521a9e0e-b73f-48ed-a2de-70d832a8ac15.png)
With no main bar transparency:
![image](https://user-images.githubusercontent.com/27446196/192159338-4590f154-1944-41d1-8534-99896f26853e.png)

Issue:
https://github.com/elParaguayo/qtile-extras/issues/108
PR:
https://github.com/elParaguayo/qtile-extras/pull/110

Current qtile config:
https://github.com/Crystal4276/qtile

NB: Thx for the updated launchbar, it looks great !

**Comment by elParaguayo** [comment]
Your qtile version is out of date. You need to update to latest git as this fix relies on a change to qtile too.

**Comment by Crystal4276** [comment]
Sorry i copy pasted the wrong version.
This is what i have installed:
Qtile-extra
[Installed: r158.10be03b-1]
Qtile
 aur/qtile-git 0.20.0.r33.gc1f50739-2 [+70 ~0.22] [Installed: 0.22.1.r5.g419e3418-1]

**Comment by elParaguayo** [comment]
Ok - those are the right versions. Let me check,..

**Comment by elParaguayo** [comment]
Can't recreate this. Widgets appear on top of the decoration for me.

**Comment by Crystal4276** [comment]
I did a bit more digging using the default configuration file.
It turns out that the issue is related to the way i called the color of rectdecoration
# Decoration setting for no grouping Rect.Decoraction
```
decor_nogroup = {
    "decorations": [
        RectDecoration(
            colour=colors[6],
            line_width= 2,
            radius=20,
            filled=True,
            padding_y=10,
            padding_x=0,
            group=False,
        )
    ],
}
```
i get the issue above.
If i set the colors explicitly i see the icons, but i can see another issue with padding ?
```
decor_nogroup = {
    "decorations": [
        RectDecoration(
            colour="#45475a",
            line_width= 2,
            radius=20,
            filled=True,
            padding_y=10,
            padding_x=0,
            group=False,
        )
    ],
```
}
![image](https://user-images.githubusercontent.com/27446196/192502682-a3c91cdf-6525-4512-a111-1dc9d6ede42d.png)

**Comment by elParaguayo** [comment]
If `colors[6]` is a list then I'm not surprised it doesn't work. The icons can only take a single solid colour.

Similarly, there's nothing I can do about the padding. The widget just fills the space behind the icon (which is a separate window). You'll need to reduce the icon size to get rid of that issue.

**Comment by Crystal4276** [comment]
I change the list to have only one single solid color and it gave the same issue.
What is weird is that all RectDecoration i'm using with for instance groupbox or launchbar doesn't have this issue with a list. Only systray is problematic.

I could tune the general aspect playing systray icon size, but there is still one quirk and i can't get rid off.
It's the end of the decoration on the right hand side that close too quickly. Playing with padding on systray or decoration doesn't help.
![image](https://user-images.githubusercontent.com/27446196/192555549-ffd37789-386c-43bf-84c4-ec7823137266.png)
If the rectdecoration could be shifted a bit more toward the right that should fix it.

**Comment by elParaguayo** [comment]
Systray is completely different to every other widget. Systray does not draw the icons in the bar. Each icon is a separate X window that is embedded into the bar window. This means we have very little control over the appearance of the icons. Adding a solid background colour is the best I can reasonably do. NB this is not the same as drawing the widget background (where we can add gradients), I am adding colour to a separate window.

As for the other point, it's interesting as it looks like everything should be shifted left a bit. One option could be to add a Spacer after the Systray, give it a fixed width and group that with the Systray widget.

There is a mechanism for adding extra width but it's not readily available for RectDecorations at the moment. Try:
```
qtile cmd-obj -o widget systray -f eval -a "self.decorations[0]._extrawidth=5"
qtile cmd-obj -o widget systray -f eval -a "self.bar.draw()"
```

If that works, we can expose the `_extrawidth` attribute to make it easier.

**Comment by elParaguayo** [comment]
> The spacer grouping doesn't work well, because the decoration is then too enlarged on the right. But this work like a charm with extrawidth=7.

Ah yes, that would make sense about the spacer. Glad the extra width worked. I'll make a change so this can be set as a parameter when configuring the decoration.

> If i understood well your comment above :"Each icon is a separate X window that is embedded into the bar window. This means we have very little control over the appearance of the icons." There is absolutely no chance to get a good result with a transparent bar ?

Unfortunately, yes, that is the issue (and it's why this is mentioned in our docs). It sucks and looks horrible but there's no easy way to fix it. I'm not aware that this issue works on other window managers but, if you can point to an example where it dows work then I can look at the code. However, for now, this is not something I expect to look at again.

**Comment by elParaguayo** [comment]
I've now added the `extrawidth` parameter as a configuration option to decorations so this should work now.

**Comment by Crystal4276** [comment]
qtile-extra :Installed: r162.54aa2ee-1
```
decor_systray = {
    "decorations": [
        RectDecoration(
            colour="#45475a",
            line_width= 0,
            radius=20,
            filled=True,
            padding_y=10,
            padding_x=0,
            extrawidth=50,
            group=False,
        )
    ],
}
```
It didn't work. Am i missing something ?

**Comment by elParaguayo** [comment]
Hmm. Did you restart qtile? (reloading config isn't enough)

What does `qtile cmd-obj -o widget systray -f eval -a "self.decorations[0]._extrawidth` output?

**Comment by Crystal4276** [comment]
Yes !
Rebooting the computer fixed it.
Thanks a lot for adding the option.

**Comment by elParaguayo** [comment]
Can we close this now or is there still an outstanding issue?

**Comment by Crystal4276** [comment]
It's all good !
