### ISSUE TITLE
Failed mouse callbacks on StatusNotifier widget

### ISSUE THREAD

**Issue by m-col** [elParaguayo/qtile-extras#130]
I finally had some minutes (of procrastination) to replace my qtile StatusNotifier with your upgraded version. Judging from the docs it appears to be relatively drop-in so I changed nothing in my config except replacing which module I loaded `StatusNotifier` from. The only parameter passed to it is `padding=20` anyway.

The widget shows icons as expected, performing the same function as the native widget correctly.

However, right-clicking to open menus fails, with this exception:
```
  File "/home/mcol/git/qtile/libqtile/bar.py", line 487, in process_button_click
    widget.button_press(
  File "/home/mcol/git/qtile/libqtile/widget/statusnotifier.py", line 656, in button_press
    self.mouse_callbacks[name]()
  File "/home/mcol/git/qtile-extras/qtile_extras/widget/statusnotifier.py", line 160, in show_menu
    self.selected_item.get_menu(callback=self.display_menu)
  File "/home/mcol/git/qtile-extras/qtile_extras/widget/statusnotifier.py", line 57, in get_menu
    if self.menu:
AttributeError: 'StatusNotifierItem' object has no attribute 'menu'
```

From a look at the widget's module it seems that `attach_menu` is never getting a chance to run so `self.menu` is never set on the item. Perhaps it is relevant that the widget was first created during a config reload, so the `host` had already start earlier in the session. This happens on icons from both deluge and keepassxc (all of my icons).

Unrelated but left-clicking on keepassxc opens keepassxc as expected, but not deluge. This might be expected behaviour (I don't know if deluge supports opening via icon click) but this error gets logged, which could either be a bug or an unclear "this is unsupported by the icon" message:
```
2022-10-11 16:30:57,027 ERROR libqtile loop.py:_handle_exception():L63 'ProxyInterface' object has no attribute 'call_activate'
NoneType: None
```

**Comment by elParaguayo** [comment]
Nice bug report. Thanks!

I'll take a look at that `attach_menu` point and think how best to handle when we're reloading the config.

One the second point, yes, it looks like the method is unsupported which probably means the icon is not following the StatusNotifier specification but we should handle it better than this.

Lastly, I've seen a few of those `NoneType: None` messages before and I've no idea where they're coming from. It's not this widget.

**Comment by m-col** [comment]
> Lastly, I've seen a few of those NoneType: None messages before and I've no idea where they're coming from. It's not this widget.

I also noticed this part today as something noteworthy, as I thought it was just the last part of this error message (following a newline character in the error message):
```
2022-10-11 16:53:18,558 ERROR libqtile loop.py:_handle_exception():L63 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
```
but in this SNI case no NoneType is involved :thinking: The `_handle_exception` method is a pattern here though, so maybe it's something to do with the data passed into that log.

**Comment by elParaguayo** [comment]
https://stackoverflow.com/questions/53162817/logging-exceptions-in-python-3
