### ISSUE TITLE
ALSA widget import error

### ISSUE THREAD

**Issue by raphaelchristin** [elParaguayo/qtile-extras#143]
Hi there,

I just added the ALSA widget to my config and it seems to cause an import error. The relevant part of my config is as follows: 

```python
alsa = dict(
     bar_color_high = colors['yellow'],
     bar_color_loud = colors['red'],
     bar_color_mute = colors['black'],
     bar_color_normal = colors['cyan'],
     device='Master',
     hide_interval=3,
     mode='bar'
 )
widget.ALSAWidget(**alsa)
```

I checked the log file and the following error shows up: 
```
2022-10-27 12:09:19,697 WARNING libqtile __init__.py:import_class():L92 Unmet dependencies for 'qtile_extras.widget.alsavolumecontrol.ALSAWidget': cannot import name 'expose_command' from 'libqtile.command.base' (/home/raphchr/.local/lib/python3.10/site-packages/libqtile/command/base.py)
```

I am not familiar with expose_command from qtile, maybe it was changed recently? 

Thanks for the help, I really appreciate the work you put into this.

**Comment by elParaguayo** [comment]
If you use the latest git version of qtile-extras then you also need to be on the git version of qtile. Qtile had a recent change which introduced the code that you're missing.

So, you've got two options here:
1) Run latest git versions of both qtile and qtile-extras
2) Stick to the tagged versions of both (this version is compatible with the latest qtile release: https://github.com/elParaguayo/qtile-extras/releases/tag/v0.22.1)

**Comment by raphaelchristin** [comment]
ah yes that would do it.

Thanks very much!
