### ISSUE TITLE
[Feature request] Add an icon_size option for the ALSA widget

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#150]
Hello elParaguayo,
Maybe i missed it ?
But it seems there is no icon_size option to adjust the size of the speaker icon.
That would be a nice addition to adjust the icon size according to bar and decoration height (cf picture below).

![Screenshot from 2022-11-02 07-49-01](https://user-images.githubusercontent.com/27446196/199400982-0d7170e4-c323-4944-bd6a-040019351881.png)

**Comment by elParaguayo** [comment]
Yes. Good point. That really should be in there.

**Comment by elParaguayo** [comment]
I think #151 should do it. Can you test?

**Comment by Crystal4276** [comment]
![image](https://user-images.githubusercontent.com/27446196/199445174-b1e17594-8b32-44ea-9350-8ef8a0c35a64.png)

The icon is smaller but there is an issue with alignement

**Comment by elParaguayo** [comment]
`padding_y`, if it's not set explicitly, will take the value from `padding`. I'm assuming this is set either in the widget itself or `widget_defaults`.

The idea of using it here was as a vertical offset adjustment but maybe that's not the right approach.

I'm not quite sure what you mean by "cut above and below".

**Comment by Crystal4276** [comment]
>I'm not quite sure what you mean by "cut above and below".
I was referring to the behavior of padding_y with Rect_decoration that reduce the apparent bar height by x pixels above and below

**Comment by elParaguayo** [comment]
OK. The effect is essentially the same. For the decoration, the value is an offset which changes where the decoration starts drawing and applies the same padding at the bottom.

For the icon, we just use the first part (i.e. the offset). However, the icon won't be cut off if it goes into the area that would be covered by the bottom padding.

**Comment by elParaguayo** [comment]
@Crystal4276 The `padding_x/y` adjustment here is awful as `padding` is typically set in `widget_defaults`.

Any objections if I just replace them with `x_offset` and `y_offset` (or something like that) so the widget is in the right place by default?

Or... remove the vertical one entirely as it should be centered vertically anyway and then we just use the standard `padding` for the horizontal offset.

Thoughts?

**Comment by Crystal4276** [comment]
> Or... remove the vertical one entirely as it should be centered vertically anyway and then we just use the standard padding for the horizontal offset.

I think this is the most simple thing to do.

**Comment by elParaguayo** [comment]
Agreed. Have pushed that change.

**Comment by elParaguayo** [comment]
If that one works for you then I'll get it merged.
