### ISSUE TITLE
Interaction of Rectdecoration and bar from ALSA widget

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#152]
Hello,

The bar from ALSA widget is not confined to the Rectdecoration.
Instead it takes the whole height of the qtile bar.

Actually what i believe would be best is an additional bar_height argument to allow even more options (even with additional borders ?).
One might want to make the bar even smaller than the RectDecoration height.

**Comment by elParaguayo** [comment]
This should be possible by adding `clip=True` to the RectDecoration configuration. Have a look [here](https://qtile-extras.readthedocs.io/en/stable/manual/ref/decorations.html#qtile_extras.widget.decorations.RectDecoration).

It's possible that I did add a commit that would break this behaviour but would be good if you could check.

**Comment by Crystal4276** [comment]
Yes, clip=true works.
