### ISSUE TITLE
[Feature request] Cosmetic improvements for menu generated by status.notifier widget

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#154]
Some cosmetic suggestions based on the rofi launcher i'm using (cf picture)

![Screenshot from 2022-11-03 19-39-38](https://user-images.githubusercontent.com/27446196/199781445-2ce1f96b-190d-4747-bab7-e0ac32fe3dbf.png)

To achieve a similar result, i'd like to use three additional options:
**- rounded corner for highlight**  (pink rounded highlight in rofi screen shot)
Using picom with rounded corner is problematic if the first highlight on the menu is rectangular.
And it's still a nice feature to have anyway.

**- font_color_highlight.** 
We have a highlight_colour option. The problem is that the color we can effectively chose for highlight is rather limited. This is because the font color of the highlighted text  cannot be changed.
As an illustration, the rofi screenshot show that with the pink highlight the text color is changed to almost black to allow its visibility.

**- font_color_disabled.** 
An option to chose the font color of items that cannot be selected/highlighted.

**Comment by elParaguayo** [comment]
Thanks.

First two make sense.

Last one should be done in that current PR: `menu_foreground_disabled` will set that colour.

**Comment by Crystal4276** [comment]
One more feature on the wishlist :)

The icon displayed on the left hand side of the menu is a bit too small.
![Screenshot from 2022-11-03 21-48-54](https://user-images.githubusercontent.com/27446196/199809720-1d68d272-331b-485d-8781-fa74aee01810.png)

An `icon_size` option would be nice.

**Comment by elParaguayo** [comment]
> One more feature on the wishlist :)
> 
> The icon displayed on the left hand side of the menu is a bit too small. ![Screenshot from 2022-11-03 21-48-54](https://user-images.githubusercontent.com/27446196/199809720-1d68d272-331b-485d-8781-fa74aee01810.png)
> 
> An `icon_size` option would be nice.

Interestingly, I've actually got the code for that already but, for some reason, I forgot to expose the configuration option!

**Comment by elParaguayo** [comment]
Have a look at #157

**Comment by Crystal4276** [comment]
Two more idea !
- Define border (width + color) for the menus.
As illustrated in the screenshot below, this could be usefull when the background color of an application is the same as the menu background.
- margin_y for menu:
Setting the y position of menus relative to qtile bar.
On the screenshot i'd like to shift the top menu position to correspond to the top of the windows under qtile bar

![Screenshot from 2022-11-06 13-04-26](https://user-images.githubusercontent.com/27446196/200164974-b1944109-084d-4e58-85f6-0341fdab88d2.png)
