### ISSUE TITLE
Overlap of menus from Status Notifier widget.

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#161]
Here's a small movie showing the successive opening of steam menu and discord menu from the Status Notifier widget.

https://user-images.githubusercontent.com/27446196/200164116-e175ad95-338d-4c62-af93-686d363c687b.mp4

The steam menu remains opened below the discord menu.

I think the expected behavior would be to kill the steam menu when opening discord menu.

**Comment by elParaguayo** [comment]
OK. So we need to check if a menu is open before opening another.
