### ISSUE TITLE
Updatig Popup Controls

### ISSUE THREAD

**Issue by DanTheMan1244** [elParaguayo/qtile-extras#165]
I have been trying to update a Popup Slider to show volume, and have not found any way to do so.

I have tried before, and just now, to call the `draw()` function on the popup as you have suggested on Reddit with no success.

This is the code I am using. It's a bit ugly but should work.

```
def diagnosticView(qtile):
    global diagnosticPopup
    diagnosticPopup = PopupAbsoluteLayout(qtile, width=800, height=2097, controls=[
    PopupSlider(max_value=150, min_value=0, pos_y=100, pos_x=100, height=400, width=500, value=getVolume()[0], bar_size=20, marker_size=1, can_focus=False)
    ], background="#000000", close_on_click=False, can_focus=False)


@lazy.function
def showDiagnosticView(qtile)
    diagnosticView(qtile)
    diagnosticPopup.show(x=10, y=50)

@lazy.function
def hideDiagnosticView(qtile):
    diagnosticPopup.hide()

@lazy.function
def updateDiagnosticView(qtile):
    diagnosticPopup.draw()
```

Thank you.

**Comment by elParaguayo** [comment]
How are you updating the value of the slider?

**Comment by elParaguayo** [comment]
`value=getVolume()[0]` will only set the value at that point. It's not a reference to call `getVolume()` each time. You need to change the control's `value` and then redraw the popup.

**Comment by DanTheMan1244** [comment]
Okay I'll try that. Sorry for the slow responses. I've been a bit busy.

For updating the value should I just call the function that defines the Popup?

**Comment by elParaguayo** [comment]
That's one way of doing it but the trouble is I don't think it will hide the old one first.

**Comment by elParaguayo** [comment]
I've started a PR (#185) that should make this easier.
