### ISSUE TITLE
[Bug] last version of qtile-extra introduce new bug with status notifer..

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#169]
On a triple monitor configured with monitor 0 as the central monitor -> Screens: [1,0,2] 

The status notifier widget is placed on screen 0. 
Menus are now displayed on screen 2 instead of screen 0 !!!!

**Comment by elParaguayo** [comment]
Sorry about that - I'll try to sort asap.

**Comment by elParaguayo** [comment]
You can edit the PKGBUILD and append  `#commit=<commit-hash>` to the end of the `source`.

**Comment by elParaguayo** [comment]
#171 should fix this.

**Comment by Crystal4276** [comment]
Yes it did.
Thanks you !

**Comment by elParaguayo** [comment]
Great. I'll try to merge both of these this morning.
