### ISSUE TITLE
[Feature Request] New highlight method for Popup Toolkit Controls

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#173]
One of the cool feature i found with archlinux-logout (by arcolinux team) is how the icon are swapped when highlighted.
They use theme with two set of icons blurred and non blurred.
When the cursor hover on one icon.svg :
![logout](https://user-images.githubusercontent.com/27446196/201345827-b954ba8e-10fb-4056-83e1-3a5745ddf7a3.svg)
It is substituted by icon_blurred.svg: 
![logout_blur](https://user-images.githubusercontent.com/27446196/201345831-62ae63ff-82fd-4765-8a40-50a78a654248.svg)

The effect is quite nice.
Is it something you'll find interesting to implement as a new highlight method?

**Comment by Crystal4276** [comment]
archlinux-logout use two separate images so option 1.

But i guess option 2 is more elegant

**Comment by Crystal4276** [comment]
Since i'm trying at the moment to make icon for that purpose, i think option 1 make sense.
When I look at the sheer number of options to apply a blur with GIMP, i believe it's probably better to provide the user the flexibility to bring his icons.

**Comment by elParaguayo** [comment]
That would certainly be easier.

**Comment by elParaguayo** [comment]
This is in #183
