### ISSUE TITLE
Issue with clipping from RectDecoration and Alsa.widget bar

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#174]
It seems the clipping from rect.decoration is not applied anymore:
![image](https://user-images.githubusercontent.com/27446196/201364886-d5389c58-87bd-4423-ae6c-b4d9f53eed9e.png)

**Comment by elParaguayo** [comment]
Argh. That's so weird. Ok - will investigate again!

**Comment by elParaguayo** [comment]
Try #175.

**Comment by Crystal4276** [comment]
Tested, all good !

**Comment by Crystal4276** [comment]
Ok, i'll report tomorrow if i seen anything

**Comment by Crystal4276** [comment]
I think you can merge that one too. No issue so far.
