### ISSUE TITLE
[Feature request] Relative positioning of popup 

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#176]
As far as i understand the show function can only center the popup in the middle of the screen or locate it with absolute coordinates. 
It could be useful to provide also relative positioning, especially when the qtile configuration is moved to different monitor configuration/resolution.

For instance, we would have those four reference points which are the screen edges: 
```top_left, top_right, bottom_left, bottom_right.```
And those two options below would shift the popup vs. those reference points:
```offset_x, offset_y```

**Comment by elParaguayo** [comment]
The `x` and `y` coordinates should be relative to the current screen. Is that not how it's working?

**Comment by Crystal4276** [comment]
![image](https://user-images.githubusercontent.com/27446196/201393191-e55e02a5-124f-4877-8d9c-5ced8d961af1.png)

At the moment it's configured like this on a 3440x1440 screen:
``` layout.show(x=3245, y=66, warp_pointer=False)```
I think it's absolute ?

**Comment by elParaguayo** [comment]
Not sure I follow. If you've got one monitor then the co-ordinates are the same.

However, if you have multiple monitors and the second one starts at x=3440 then setting an x, y position of 0, 0 on that screen would be in the top left of that screen.

**Comment by Crystal4276** [comment]
I was not thinking about multiple monitor in the first place, but now that i tested opening the popup on the two secondary monitors i see some issues that i think are due absolute positioning.

Screen configured like this: [1;0;2]
Screen 1: 1920x1080
Screen 0: 3440x1440
Screen 2: 1920x1080

layout.show(x=3245, y=66, warp_pointer=False)

Opening of popup on screen 1 -> popup appears on screen 0
![image](https://user-images.githubusercontent.com/27446196/201399361-d6c15575-0daf-4631-815b-b35b1ee30529.png)
Opening of popup on screen 0 -> popup appears as expected
![image](https://user-images.githubusercontent.com/27446196/201399474-f4dde919-2b72-4dcc-a0fb-2ec8fdd1cbd0.png)
Opening of popup on screen 2 -> popup is not visible offscreen 
![image](https://user-images.githubusercontent.com/27446196/201399629-0ddabf79-052a-42ff-b81a-d10ce1704fbf.png)

If we had an option of relative positioning vs. screen edges (top_left, top_right, bottom_left, bottom_right), this issue would be circumvented.

**Comment by elParaguayo** [comment]
That behaviour looks like I'd expect. If you try X=3245 on screen 1 which has a width less than that then I would expect it to appear where it's shown.

Your function could get the dimensions of the current screen and calculate the appropriate X and Y coordinates before passing these to `show()`.

**Comment by Crystal4276** [comment]
Ok, i'll research how to do it.
Thanks.

**Comment by elParaguayo** [comment]
Thinking about this some more, I think your request is reasonble.

How about if we added a `relative_to` option which took a number based on the screen being broken into a 3 x 3 grid:
```
 1  2  3
 4  5  6
 7  8  9
```
So `relative_to=1` would be relative to top left corner (default). `relative_to=3` would be relative to top right corner etc.

**Comment by Crystal4276** [comment]
Well, that's even more complete !
Yes, of course, i think that's great.

**Comment by elParaguayo** [comment]
Here you go: #178
