### ISSUE TITLE
Some thought about kill events for popup

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#181]
I don't know if it is a bug or a feature request.

The video here show the difference between how the menu from statusnotifier is killed vs. popup:

https://user-images.githubusercontent.com/27446196/201473913-24d33b4f-e07a-4c4c-8057-b9d004be2f84.mp4

When the pointer is leaving the menu from statusnotifier, the windows get killed with some delay. 
For popup, the latter remains displayed. Even clicking on the desktop wallpaper doesn't kill it. 
To kill popup either:
- ESC button is pressed, 
- Pointer changes the focus to an opened application
- A new application is opened

For consistency, I was wondering if popup could match the behavior of menus from statusnotifier.

**Comment by elParaguayo** [comment]
It's not a bug. That's how the menu works.

It is possible to add the same functionality to all popups but I may have it disabled by default.

**Comment by Crystal4276** [comment]
At the moment, i'm using the popup more like a fancy menu. So i'm a bit biased regarding the expected outcome.

I assume that other users have built complex popup with a lot of stuffs in. 
Having the popup killed as soon as the pointer leave the window could feel like a regression.

Hum...could you maybe add a toggle to switch behaviors ?

**Comment by elParaguayo** [comment]
Agreed. That's what I meant about having it disabled by default.

**Comment by elParaguayo** [comment]
#181 should do this for you.
