### ISSUE TITLE
widget.CurrentLayoutIcon cannot find custom icons

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#189]
Going deeper in this rabbit hole, i'm trying to use custom icons for layout.
```python
 widget.CurrentLayoutIcon(
                       scale = 0.66, 
                       custom_icon_paths = "~/.config/qtile/assets/layout",
                       #use_mask = True, 
                       foreground=colors[3],
                       ), 
```
The widget does not detect the icons.
My guess is that the `~` is not expanded.

**Comment by elParaguayo** [comment]
Does it work if you replace it with `os.path.expanduser("~/.config/qtile/assets/layout")`?

**Comment by elParaguayo** [comment]
Also, this bug is also in the main repo. Looking at that code, no `expanduser` call is added to that folder but, more importantly, `custom_icon_paths` should be a **list** of folders.

**Comment by Crystal4276** [comment]
Ok !
So this  `custom_icon_paths = ["~/.config/qtile/assets/layout"]` didn't work.
But this `custom_icon_paths = [os.path.expanduser("~/.config/qtile/assets/layout")]` worked

**Comment by elParaguayo** [comment]
Yes. So there is a bug in the main qtile version of the widget as it never calls `os.path.expanduser` on those custom paths.

**Comment by Crystal4276** [comment]
Ok i will close this one and open on qtile.

Although i found something else. It seems the widget can't open .svg files.
That one is qtile-extra ?

**Comment by elParaguayo** [comment]
No. That's qtile as well. What OS are you on?

**Comment by Crystal4276** [comment]
Arch linux.

widget.image has not issue to load .svg.

Just the current layout widget is problematic

**Comment by Crystal4276** [comment]
How i found something interesting.
The widget can work with .svg but only if there is no .png in the same folder
