### ISSUE TITLE
Wayland: No StatusNotifier icons for nm-applet and udiskie

### ISSUE THREAD

**Issue by bodograumann** [elParaguayo/qtile-extras#201]
Using wayland, qtile 0.22.1 and StatusNotifier from this repo.
Both network-manager-applet and udiskie have appindicator support implemented, but I cannot see the icons in the bar.
I am starting them in my autostart script as
```
nm-applet --indicator &
udiskie --appindicator &
```

Btw. https://github.com/qtile/qtile/pull/3060 is merged, so https://github.com/elParaguayo/qtile-extras/blob/54bca422ab3a2d357d74ccdf9caf4572a832801a/qtile_extras/widget/statusnotifier.py#L107-L122 should be removed.

**Comment by elParaguayo** [comment]
Do you get any error messages in the logs?

**Comment by bodograumann** [comment]
Ah, this seems to be logged:
> 2022-11-25 15:30:52,591 WARNING libqtile statusnotifier.py:start():L168 Cannot find icon in current theme and no icon provided by StatusNotifierItem.

I also get a lot of
> 2022-11-25 13:02:46,735 WARNING libqtile tasklist.py:_configure():L315 You must install pyxdg to use theme icons.
even though I have python-pyxdg installed (via pacman) and can `import xdg`...

**Comment by elParaguayo** [comment]
Are you running a virtual environment? It certainly feels like it can't find the xdg library.

**Comment by elParaguayo** [comment]
I've just tried `udiskie` and also don't get an icon so will investigate more when I can.

**Comment by elParaguayo** [comment]
Another issue is, if you haven't set the icon theme then XDG looks for icons in the `hicolor` theme. From what I can tell, the icons used by `udiskie` are not provided by that theme.
```
>>> import xdg.IconTheme
>>> xdg.IconTheme.getIconPath("drive-removable-media")
>>> xdg.IconTheme.getIconPath("drive-removable-media", theme="breeze")
'/usr/share/icons/breeze/preferences/32x32/drive-removable-media.svg'
```

**Comment by Crystal4276** [comment]
I have both working fine in status.notifier widget
I'm using Papirus icons:
![image](https://user-images.githubusercontent.com/27446196/204088533-a0add1f9-bcb0-490e-8f3e-0b7b7006fe23.png)

**Comment by elParaguayo** [comment]
I'd also add that the icon is not a qtile-extras issue either, that's from the main qtile version of the widget. qtile-extras just adds the menus.

**Comment by bodograumann** [comment]
The problem with xdg, is that there is another package [xdg](https://pypi.org/project/xdg/) that is shadowing pyxdg.
I'll remove it from my user packages and see whether I can replace it with pyxdg where necessary.

Btw. I created the ticket here, because I read a similar issue on the qtile repo and the reporter there was pointed to the extras repo.

**Comment by bodograumann** [comment]
Thank for you help!
After uninstalling the xdg package and defining an explicit icon theme (of 'breeze-dark') both icons now show for me :-)

**Comment by elParaguayo** [comment]
Great. Thanks for confirming.
