### ISSUE TITLE
`RectDecoration` disappears when screen size changes

### ISSUE THREAD

**Issue by jx11r** [elParaguayo/qtile-extras#209]
![image](https://cdn.discordapp.com/attachments/955650645833162822/1030887920309108837/unknown.png)

_Originally posted by @jx11r in https://github.com/elParaguayo/qtile-extras/issues/197#issuecomment-1328535605_

**Comment by elParaguayo** [comment]
Oh. That's a shame. Did you post an issue about this originally? #197 seems to fix two issues posted by another user.

**Comment by jx11r** [comment]
Hmm... nope, I didn't

**Comment by elParaguayo** [comment]
Are you able to do a `git bisect` to work out which commit broke this?

If not, can you send me the config for that green/yellow/blue section of your bar and I'll look to test locally (although I'm not sure how much time I have this week).

**Comment by elParaguayo** [comment]
Ok, I can recreate this. I'll do a bisect later as I did fix this a while ago.

**Comment by elParaguayo** [comment]
Looks like this broke it: 60fd1d10

**Comment by jx11r** [comment]
> Are you able to do a git bisect to work out which commit broke this?

Sorry, I wasn't at home

> Looks like this broke it: [60fd1d1](https://github.com/elParaguayo/qtile-extras/commit/60fd1d10e3894eacac257af0cedd5ac433779d08)

Yeah, you're right
