### ISSUE TITLE
massive slowdown when using the ALSAWidget

### ISSUE THREAD

**Issue by ronniedroid** [elParaguayo/qtile-extras#210]
I am on Fedora linux 37, qtile and qtile_extras latest git build. 

Starting Qtile, changing monitor configuration and reloading the config takes about 5 to 15 seconds. I tested with UPowerWidget and ALSAWidget, ALSAWidget was the problem. I have no tested any other widgets (Except for the LightControll widget in the pull request I submitted, which is based on the ALSAWidget).

**Comment by ronniedroid** [comment]
nothing in the logs. The LightControl widget I based on it has the same problems too.

**Comment by ronniedroid** [comment]
`both`

**Comment by elParaguayo** [comment]
Can you share your config (ideally a minimal version that still has this behaviour) and the steps to trigger the issue?

I can't recreate it at the moment.

**Comment by Crystal4276** [comment]
I was curious to test this also, and I can confirm i see the same behavior.
From SDDM i can start qtile almost instantly. 
If ever ALSAwidget is there with the below config, then there ~ 5s delay before qtile start.
```python
                 widget.ALSAWidget(
                       mouse_callbacks={"Button3": lazy.spawn("pavucontrol")},
                       mode='both',
                       theme_path="/usr/share/icons/Papirus-Dark",
                       icon_size=36,
                       fontsize=20,
                       padding=5,
                       bar_width=60,
                       bar_colour_high=colors[10],
                       bar_colour_loud=colors[15],
                       bar_colour_normal=colors[13],
                       bar_colour_mute=colors[7],
                       foreground=colors[5],
                       background=colors[7],
                       update_interval=5,
                       hide_interval=2,
                       **decor_general,
                       ),
def init_colors():
    return [["#cdd6f4", "#cdd6f4"], # color 0 Text (Blue) 
            ["#1e1e2e", "#1e1e2e"], # color 1 Base #1e1e2e
            ["#9399b2", "#9399b2"], # color 2 Overlay 2 
            ["#f5c2e7", "#f5c2e7"], # color 3 Pink 
            ["00000000", "00000000"], # color 4 Transparent
            ["#f3f4f5", "#f3f4f5"], # color 5 White
            ["#45475a", "#45475a"], # color 6 Surface 0
            ["11111bbf"], # color 7  Crust 75% transparency # Base 85% transparency 1e1e2ed9
            ["#f3f4f500", "#f3f4f500"], # color 8 White 66 % tranparency for highlight
            ["#11111b", "#11111b"], # color 9 Crust
            ["#fab387", "#fab387"], # color 10 Peach
            ["#f9e2af", "#f9e2af"], # color 11 Yellow
            ["#a6e3a1", "#a6e3a1"], # color 12 Green
            ["#94e2d5", "#94e2d5"], # color 13 Teal (Blue/Green)
            ["#eba0ac", "#eba0ac"], # color 14 Maroon (Reddish/pink)
            ["#f38ba8", "#f38ba8"], # color 15 Red
            ["#89dceb", "#89dceb"], # color 16 Sky (Blue)
            ["#585b70", "#585b70"], # color 17 Surface 2 (grey)
            ["#74c7ec", "#74c7ec"], # color 18 Sapphire
            ["#89b4fa", "#89b4fa"], # color 19 Blue
            ["#b4befe", "#b4befe"], # color 20 Lavender
           ] 
colors = init_colors()

```
Removing the decoration doesn't help.

**Comment by Crystal4276** [comment]
I tried with `widget.ALSAWidget()` (no config), and i see the same issue. 
Removal of config maybe remove 1-2 s delay.

**Comment by elParaguayo** [comment]
Thanks. This is very odd but clearly there's an issue somewhere. 

Frustrating that I can't recreate it but let me test some more tonight.

**Comment by ronniedroid** [comment]
Sorry was asleep and did not reply, I hope the config provided by @Crystal4276 is enough.
I just finished setting up a virtual machine (Fedora 37 i3 spin) to test in a minimum environment, and had the same problem. too bad no logs are being produced to indicate where this delay is happening.

**Comment by elParaguayo** [comment]
My suspicion is that it's something to do with when the widget is configured.

In your `light` widget, could you try commenting out the `self.get_brightness()` line and see if that makes a difference.

If it doesn't, can you try removing all references to the `ExtendedPopupMixin` i.e. remove the import, the inheritance in your class definition and then these two lines:
``` python
        ExtendedPopupMixin.__init__(self, **config)
        self.add_defaults(ExtendedPopupMixin.defaults)
```

**Comment by ronniedroid** [comment]
I tried both, non of them made a difference. The other widget I am working on `latte.py` is very simple and has no popups and it still slows down, not as much as the `alsa` and `light` ones, but still noticeable.

**Comment by elParaguayo** [comment]
Can you share the `latte.py` code? I can see if there are any common themes.

**Comment by ronniedroid** [comment]
sure, https://github.com/ronniedroid/qtile-extras/blob/latteWidget/qtile_extras/widget/latte.py

**Comment by elParaguayo** [comment]
OK. For the alsa widget, can you just set mode to `bar`? All of these widgets try to load images during configuration so I wonder if that's the issue.

**Comment by elParaguayo** [comment]
How are you changing the volume?

**Comment by elParaguayo** [comment]
Through the widget or directly?

**Comment by ronniedroid** [comment]
I see, my bad.

**Comment by elParaguayo** [comment]
Back to the original issue, it seems like there's a problem with loading images.

What distro are you on? (@Crystal4276 you too please)

**Comment by ronniedroid** [comment]
Fedora 37

**Comment by Crystal4276** [comment]
I tried 'both' and 'bar' there are no big differences between the two (bar a bit faster).

**Comment by elParaguayo** [comment]
Hmm. I'm on Arch too. Let me test this widget with icons tonight.

**Comment by elParaguayo** [comment]
Still can't recreate this. Not seeing any difference in startup time between when I'm using the alsa widget and when I'm not. `reload_config()` is almost instant too.

**Comment by ronniedroid** [comment]
This is weird, not sure if this will help you debug, I am on python 3.11.0, latest git version of qtile and qtile-extras, linux kernel 6.0.8.

**Comment by ronniedroid** [comment]
@elParaguayo what icon theme are you using? it is loading gnome icons fast, no slow down at all, but Papirus and Numix-circle are slow.

**Comment by elParaguayo** [comment]
Tried with Paper. However, I'm not entirely convinced it's this given Crystal4276's comments (plus this widget uses the same image loader as standard qtile widgets so you should see the same issue with them too).

**Comment by Crystal4276** [comment]
I couldn't try gnome icons on Arch (because the volume icons were not there -> crashed of widget).
So i checked other icon sets.
I saw some variability in loading speed. For instance `kora` is noticeably faster than `Papirus`.

However, whatever the icon set, startup remains very much slower compared to no ALSA widget

**Comment by elParaguayo** [comment]
But it's still slow when not using icons at all?

**Comment by Crystal4276** [comment]
Yes, using ' bar' mode is still slow compared to no widget.

**Comment by ronniedroid** [comment]
I have no slowdown using `bar` mode, and no slowdown with `icon` and `both` mode using gnome icons

**Comment by ronniedroid** [comment]
I think your theory is correct. My latte widget has only two icons and it loads faster than the other two.

**Comment by Crystal4276** [comment]
I went to select and extract only the 4 icons needed to run the widget and placed them alone in
`theme_path="/home/crystal/.config/qtile/assets/bar_icons"`
Performance back to normal.

**Comment by Crystal4276** [comment]
One additional thought about what i think is still weird.
I'm running Status.Notifier which is also configured to look for the 'papirus' icon folder.
Why this widget is not impacting loading time as much as ALSA.widget ?

**Comment by elParaguayo** [comment]
`StatusNotifier` uses the `xdg` module to locate icons whereas the alsa widget uses qtile's built in code which is clearly less efficient but is more flexible.

I think the xdg module limits its search to certain folders based on icon size.

**Comment by elParaguayo** [comment]
> I went to select and extract only the 4 icons needed to run the widget and placed them alone in `theme_path="/home/crystal/.config/qtile/assets/bar_icons"` Performance back to normal.
> 
> EDIT: loading time is still (much) faster without Alsa.widget. (almost instant vs. 1-2 s loading time)

It does feel like there's another issue here too.

Can you try commenting out the `self.get_volume()` line in the `_configure` method and see if that has any impact?

**Comment by Crystal4276** [comment]
> Can you try commenting out the `self.get_volume()` line in the `_configure` method and see if that has any impact?

You found it !!!!!
Commenting that line solve the problem.
Now, loading is instant.

**Comment by elParaguayo** [comment]
Ok. However, if reading the volume is slow for you then this widget may not be much use for you.

Can you try setting the volume through the widget (using "volume_up/down ()" commands) and see how responsive the widget is for you. I'm wondering if `amixer` is slow for you.

**Comment by Crystal4276** [comment]
> Can you try setting the volume through the widget (using "volume_up/down ()" commands) and see how responsive the widget is for you. I'm wondering if `amixer` is slow for you.

No issues on that side. The volume is changed instantly.
I have been using this widget functionality for a while.

**Comment by Crystal4276** [comment]
Commenting that line also dramatically increased qtile reload config speed.

**Comment by elParaguayo** [comment]
Thanks both for the help debugging 

I'll remove that offending line from `_configure`.

As for the icons, I could try bumping that into a background progress to make them load _after_ the widget is configured.

**Comment by ronniedroid** [comment]
I see no difference when removing the `self.get_volume()` from `_configure`.

Also, the alsa widget when using the gnome Icons works really well, no slowdowns. 

I changed the icons to a cairo drawing in my light widget and it is working perfect no slowdowns at all.

Maybe I can try making the volume Icon a cairo drawing too, if you wish.
