### ISSUE TITLE
cannot import name 'expose_command'

### ISSUE THREAD

**Issue by AngelBerihuete** [elParaguayo/qtile-extras#224]
Dear qtile-extras users,

recently I've installed qtile-extras in order to use WiFiIcon. But qtile.log shows

```bash
WARNING libqtile __init__.py:import_class():L102 Unmet dependencies for 'qtile_extras.widget.network.WiFiIcon': cannot import name 'expose_command' from 'libqtile.command.base' (/usr/lib/python3.10/site-packages/libqtile/command/base.py)
```

I've installed qtile-extras by clonning the repo and run python3.10 setup.py install

Please, any clue to resolve this issue?

**Comment by elParaguayo** [comment]
See the note at the top of this page: https://qtile-extras.readthedocs.io/en/latest/manual/install.html

You've got the tagged release of qtile installed so you can either:
- install the latest git release of qtile; or
- install the matching tagged release of qtile-extras (https://github.com/elParaguayo/qtile-extras/releases/tag/v0.22.1)

**Comment by AngelBerihuete** [comment]
Finally I have installed the matching tagged release of qtile-extras and all works fine!

Many thanks @elParaguayo
