### ISSUE TITLE
nm-applet and blueman applet not showing icons with Statusnotifier

### ISSUE THREAD

**Issue by drishal** [elParaguayo/qtile-extras#229]
For some reason there is no icons displayed for blueman applet or statusnotifier under qtile wayland
OS: Arch Linux
Qtile extras git AUR ( r252.395320f-1 ) 
```

 $  qtile --version                    
0.22.2.dev113+g1102157a
```

(qtile-wayland git from aur)

In the logs there is only this line

`libqtile statusnotifier.py:start():L160 Cannot find icon in current theme and no icon provided by StatusNotifierItem `

**Comment by drishal** [comment]
I already have a bunch of icons installed and tried setting it to the icon
themes (as under /usr/share/icons)

**Comment by drishal** [comment]
one small question, how do I check which icon themes are actually accessible by qtile? 
( I think that could be the issue where StatusNotifier is somehow not able to find the icon themes)

**Comment by elParaguayo** [comment]
Can you run the following commands in a python terminal session please and paste the output here:
```
>>> from xdg.IconTheme import getIconPath
>>> getIconPath("blueman-tray", theme="Papirus-Dark")
```

> (also yes I need the context menu so that eventually I can use the drop down for nm-applet, blueman, discord etc

qtile-extras adds the code for the context menu but does nothing with the icons. All the icon code is inherited from the main qtile version of the repo. So, any issues with icons should be posted to the qtile repo. Any issues with the context menu are dealt with here.

However, no need to create a separate issue for now. I'll deal with this one here.

**Comment by drishal** [comment]
> Can you run the following commands in a python terminal session please and paste the output here:
> 
> ```
> >>> from xdg.IconTheme import getIconPath
> >>> getIconPath("blueman-tray", theme="Papirus-Dark")
> ```
> 
> > (also yes I need the context menu so that eventually I can use the drop down for nm-applet, blueman, discord etc
> 
> qtile-extras adds the code for the context menu but does nothing with the icons. All the icon code is inherited from the main qtile version of the repo. So, any issues with icons should be posted to the qtile repo. Any issues with the context menu are dealt with here.
> 
> However, no need to create a separate issue for now. I'll deal with this one here.
```
>>> from xdg.IconTheme import getIconPath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xdg.IconTheme'
```

WTH :eyes: 
I seem to have `python-pyxdg` 0.28-1 installed...Interesting
Seems like newer versions might have removed this? or I am missing some other dependency?

**Comment by drishal** [comment]
I think I just realised my mistake, there was python xdg installed on my home path using pip, while at the same time  I also had python-pyxdg installed systemwide
Removed the one from the user side and now the issue seems to have been resolved (can now load blueman applet and nm applet without issue
Btw, is this menu without  icons normal? 

![image](https://user-images.githubusercontent.com/32875739/212292284-79de8cf2-d4da-471e-9dae-83bc6cc9f8b3.png)

**Comment by elParaguayo** [comment]
That's correct for now. The only icon support in menus at the moment is when the menu provides icon data rather than an icon name.

However, that's only because I built the code using an app that provided icons that way. I didn't realise icon names could also be provided.

I should be able to add that relatively easily. Thanks for pointing it out!

**Comment by drishal** [comment]
> That's correct for now. The only icon support in menus at the moment is when the menu provides icon data rather than an icon name.
> 
> However, that's only because I built the code using an app that provided icons that way. I didn't realise icon names could also be provided.
> 
> I should be able to add that relatively easily. Thanks for pointing it out!

Ah ok. So should I keep the issue open for fixing the menu icons?
Or maybe open a new issue for it?

**Comment by elParaguayo** [comment]
We can keep this one open and I'll close it once I've got the change working.

**Comment by elParaguayo** [comment]
Have submitted a PR with the relevant changes. Funnily enough, all the code was already there, I just left out the part that told the menus to draw icons when it received an icon name. As a result, this was pretty quick to do.

**Comment by elParaguayo** [comment]
Ok. That fix is merged so, if you download the latest git version, you should, hopefully, get icons in your menus (provided your icon theme provides the relevant icons).

**Comment by drishal** [comment]
We now have another issue: the popup menus are cut: 
![image](https://user-images.githubusercontent.com/32875739/212450871-71f49080-db34-4893-b4a2-4642f94420c7.png)

**Comment by elParaguayo** [comment]
I wouldn't call that an issue as the submenus work, they're just not displaying as you expected them to.

The way it's shown is how I've implemented it as I wanted basic functionality to display menus. It should be possible to have them display as you show but it's just not a priority for me at the moment.

**Comment by drishal** [comment]
👍
