### ISSUE TITLE
Visualizer widget consumes a lot of CPU

### ISSUE THREAD

**Issue by gibranlp** [elParaguayo/qtile-extras#232]
Hi, i've had some qtile becoming very slow issues for some time, and recently i found that is the visualizer widget, i can only i see on Htop that qtile starts consuming more and more cpu, until it becomes unusable, and when its restarted works and the CPU starts again slowly going up.

Once i remove the visualizer widget qtile works fine again

qtile -v
0.22.2.dev115+g653c52c2

I have qtile-git and qtile-extras-git installed.

I dont know what more information i can provide, i have no logs or anything of this.

Thanks.

**Comment by elParaguayo** [comment]
Yup - this is definitely very buggy. I've seen the same behaviour too and I agree that it's pretty unusable.

I'll need to look at it again but I fear I may end up having to kill it if I can't find a fix.

**Comment by gibranlp** [comment]
If i can help you with some tests, let me know.

**Comment by elParaguayo** [comment]
Long shot but can you try this:
``` diff
diff --git a/qtile_extras/widget/visualiser.py b/qtile_extras/widget/visualiser.py
index 2d4adcd..f6e5107 100644
--- a/qtile_extras/widget/visualiser.py
+++ b/qtile_extras/widget/visualiser.py
@@ -235,6 +235,8 @@ class Visualiser(base._Widget):

         self._draw_count = 0
         self._timer = self.timeout_add(self._interval, self.draw)
+        surface.finish()
+        surface = None

     def finalize(self):
         self._stop()
```

**Comment by elParaguayo** [comment]
@gibranlp Did you have a chance to try the above change to see if it helps?

**Comment by gibranlp** [comment]
I tried it, but with this parameters the widget show nothing at all, i get the square of the widget but no bars inside.

![Screenshot_01-02-23](https://user-images.githubusercontent.com/2806964/221585544-986b7d88-e270-4ab3-adf9-19d18f10c7f0.png)

**Comment by elParaguayo** [comment]
Wow. That makes no sense.

Doesn't impact appearance for me at all.

**Comment by gibranlp** [comment]
I removed qtile extras, madethe changes in the repo and installed it again.

![Screenshot_40-02-23](https://user-images.githubusercontent.com/2806964/221594941-dbb915b0-352f-4c3d-92cf-e0399b21c28b.png)

Now i get the bars, and Qtile is around 20-25% of cpu, i'll keep using it today, and let you know if get a freeze

**Comment by gibranlp** [comment]
Im at the fourth song, and qtile is already at 95% of CPU

**Comment by elParaguayo** [comment]
OK - so it didn't work. Shame.

**Comment by elParaguayo** [comment]
I don't understand why the CPU usage increases over time. Back to the drawing board...

**Comment by elParaguayo** [comment]
> Im at the fourth song, and qtile is already at 95% of CPU

Just to check - is it `qtile` that's at 95% or is it the `cava-draw` script?

**Comment by gibranlp** [comment]
Qtile itself

**Comment by elParaguayo** [comment]
Can you try #294 (if you're still using Qtile!)

**Comment by elParaguayo** [comment]
@gibranlp I got an email with your reply but I don't see it posted here. However, I've fixed that bug that you mentioned.
