### ISSUE TITLE
How do I create my own menu?

### ISSUE THREAD

**Issue by epicgamer256705** [elParaguayo/qtile-extras#236]
How do I create my own menu like the ones in globalmenu and statusnotifier so that when I click on a custom widget I will have a menu?

**Comment by elParaguayo** [comment]
Have a look at the `LiveFootballScores` widget.

The key points are:
- the widget inherits the `MenuMixin` which is initialised during `__init__()`. NB ordering of the commands is important so take a look at that widget.
- there's a method to generate the menu items ( `self._get_match_list()`)
- the items are passed to `self.display_menu`
- this call is wrapped in another method which is bound to a mouse button.

**Comment by epicgamer256705** [comment]
How would I change the menu background I tried add menu_background to my widget_defaults

**Comment by epicgamer256705** [comment]
When I change menu_font or highlight_colour in my widget_defaults it doesn't change anything in the menu

**Comment by elParaguayo** [comment]
Interesting. I wouldn't actually expect widget_defaults to work on statusnotifier either! There's nothing special that that widget does.

To make it work with widget_defaults, I'd need to change the code of the mixin. So, for now, you'd need to add the config to the widget itself.
