### ISSUE TITLE
WiFiIcon widget probably not working with tethered interfaces

### ISSUE THREAD

**Issue by piotr-marendowski** [elParaguayo/qtile-extras#240]
I tried to set up the WiFiIcon widget, but it doesn't work for me, then tried same interface with Net widget which works. I tether my connection, and cannot try with WiFi or Ethernet, so maybe someone would be able to test it?

**Comment by elParaguayo** [comment]
`WiFiIcon` inherits from qtile's `Wlan` widget, not the `Net` one so I'm guessing that, if you tried the `Wlan` widget, it also wouldn't work for you.

**Comment by piotr-marendowski** [comment]
Yes, can confirm that `Wlan` widget doesn't work either, maybe it corresponds to `iwlib`'s  "Interface doesn't support scanning.".
