### ISSUE TITLE
Text in docs isn't highlighted

### ISSUE THREAD

**Issue by piotr-marendowski** [elParaguayo/qtile-extras#241]
It looks like this:
![screen1](https://user-images.githubusercontent.com/37738748/224475088-25fa458a-02a9-4c21-b039-313b0796de17.png)
When I presume it should look like this:
![screen2](https://user-images.githubusercontent.com/37738748/224475125-20fe69ea-4b4c-4b9a-94ec-caabd08b4417.png)
I think that this highlighted text should have three grave accent characters as it is written in markdown. I would submit a PR, but I don't know how this site works and what files to edit.

**Comment by piotr-marendowski** [comment]
Closing

**Comment by elParaguayo** [comment]
You can leave it open, it's just not high priority for me
