### ISSUE TITLE
[feature request] Mouse callabacks co-working of the same decorated widgets 

### ISSUE THREAD

**Issue by piotr-marendowski** [elParaguayo/qtile-extras#242]
Hi, I don't think If I could do something like that so I post it here as a feature request. Concept: When two widget with the same color of decoration join together (which I think is amazing and looks awesome) they inherit the same mouse callbacks (because if they would join their functions it would be a mess I think). For example Image widget with the Clock widget joined together would have the same mouse callback: opening a calendar. There are some issues: what will happen if they have the same buttons allocated? I don't know, maybe it wouldn't work and send an error message that they cannot have the same buttons. It would be rather a messy thing to implement, but it is a feature request, so thanks for considering anyway! :)

**Comment by elParaguayo** [comment]
Thanks for the suggestion.

To be honest, I don't think this is something that needs to be fixed. It's easy enough to set mouse callbacks when configuring the widgets and there are no changes needed when joining widgets (unlike the decorations which can change their appearance).

**Comment by piotr-marendowski** [comment]
You know what? I didn't even though about adding mouse callbacks to Image widgets, my god I'm so dumb, I'll try it later.
