### ISSUE TITLE
status notifier not showing discord icon

### ISSUE THREAD

**Issue by mcnuggetsx20** [elParaguayo/qtile-extras#245]
Status notifier doesn't show the discord tray icon. When i replace it with the Systray widget the icon pops up just fine.

**Comment by elParaguayo** [comment]
Are you on the latest git version? This should be fixed.

**Comment by mcnuggetsx20** [comment]
I'm on 0.22.2
```
>$ qtile --version
0.22.2.dev102+gf0d07ecf
```

**Comment by elParaguayo** [comment]
That commit is from back in January. We (hopefully) fixed this issue recently so try updating qtile and qtile-extras to get those fixes.

**Comment by mcnuggetsx20** [comment]
Oh yes, now everything works. Thanks a lot!
