### ISSUE TITLE
WiFiIcon import error

### ISSUE THREAD

**Issue by FlyingPotato-131** [elParaguayo/qtile-extras#246]
I'm trying to use the WiFiIcon after updating my system but it tries to import libqtile.command.base.expose_command which doesn't seem to exist anymore, so it breaks on loading

**Comment by elParaguayo** [comment]
Other way around. `expose_command` isn't in the 0.22.1 release of qtile.

So you either need the git version of qtile or the 0.22.1 version of qtile-extras.

**Comment by FlyingPotato-131** [comment]
yooo it works, thanks a lot)
