### ISSUE TITLE
StatusNotifier widget not working with certain apps

### ISSUE THREAD

**Issue by ezntek** [elParaguayo/qtile-extras#251]
The title says a lot, but basically, the only app that would show up in the status notifier is the blueman indicator/applet or whatever you'd want to call it, some apps just will straight up not work.

[here](https://imgur.com/a/oRPVIyG) is blueman (works fine)
[here](https://imgur.com/a/Q2b3uhF) is Armcord (not working) (Discord, Armcord and nm-applet all dont work, they look the same).

Running, say, armcord and blueman together shows just blueman, no trace of armcord.

I'm using NixOS and the package from nixpkgs, if that helps.

I did see #239 which sounds a lot like my problem, except that the amount of connected monitors doesnt affect anything, and i also did see #238 , if that helps.

**Comment by elParaguayo** [comment]
Probably a combination of: https://github.com/qtile/qtile/issues/4224 and #243

**Comment by ezntek** [comment]
ill prolly have to build a local derivation if i want the fixes, so ill work on that later on. thanks, though.
