### ISSUE TITLE
broken widget upon replacing qtile widget with qtile widget

### ISSUE THREAD

**Issue by f40a3204** [elParaguayo/qtile-extras#252]
The original widgets are broken after replacing `from libqtile import widget` with `from qtile_extras import widget`

this is how it looks:
![2023-06-04-153901_1920x1080_scrot](https://github.com/elParaguayo/qtile-extras/assets/116639116/a6558635-b873-4da8-8e4d-8761410c5b6e)

how it looked before:
![image](https://github.com/elParaguayo/qtile-extras/assets/116639116/5763fb15-164a-4967-800d-e58ed358c717)

config:
https://pastebin.com/ggagnqyp

**Comment by elParaguayo** [comment]
Thanks. What versions are you using of qtile and qtile-extras?

**Comment by elParaguayo** [comment]
Your version of qtile is too old. There's a change to `Systray` in qtile which you need.

**Comment by elParaguayo** [comment]
which distro are you on? 0.19.0 is really quite old now.

**Comment by elParaguayo** [comment]
pip should get you the latest release so try upgrading.

**Comment by elParaguayo** [comment]
Hmm. Something's broken.

I've just tried installing qtile via pip and it's installed 0.19.0. Is that what happened to you?

**Comment by elParaguayo** [comment]
OK. This is a bit painful but can you check something for me. In a python shell do the following:
```
>>> from cairocffi import cairo
>>> cairo.cairo_xcb_surface_create
```
Let me know if that gives you an error or not and we'll go from there!

**Comment by elParaguayo** [comment]
Great!

Can you do: `pip install --use-deprecated=legacy-resolver --no-build-isolation qtile==0.22.1`

**Comment by elParaguayo** [comment]
Yes. There's something weird with the version numbering (we'll look into that) but, if the widgets are now working, you'll be on the latest master.
