### ISSUE TITLE
Aur package is not installing 0.0.1 version

### ISSUE THREAD

**Issue by elkrien** [elParaguayo/qtile-extras#26]
In Arch linux when I install qtile-extras from AUR packages it shows that there is a new version (0.0.1) but when You try to update it keeps installing r91 and shows that there are updates. 
![image](https://user-images.githubusercontent.com/78103450/146641230-f7d36f93-541a-4f9c-bbc5-53d2892b8af7.png)
![image](https://user-images.githubusercontent.com/78103450/146641250-4167f1c9-5ae0-4ee6-a464-e6f4ec5cfec9.png)

**Comment by elParaguayo** [comment]
Thanks. Have just pushed an updated version of the PKGBUILD to the AUR.

I'm assuming the issue was with the default pkgver in the file.
