### ISSUE TITLE
Powerline ordering issue showed up in recent versions.

### ISSUE THREAD

**Issue by DeeeeLAN** [elParaguayo/qtile-extras#262]
![image](https://github.com/elParaguayo/qtile-extras/assets/12877032/43d2aede-390c-450c-b134-8c325d767ee7)

It was working fine around May, so something since then has caused this layout issue. It is interesting it is only this one spot I am having that layout issue, despite having another 13 or so spots where the powerline is present.

**Comment by elParaguayo** [comment]
Can you make a minimal config that reproduces the issue?

Is that systray or statusnotifier?

**Comment by elParaguayo** [comment]
Is this still an issue?

**Comment by DeeeeLAN** [comment]
yes sorry, my config is complicated so getting a minimal reproducible example was enough work that I pushed it off. The orange one is systray and the red one is statusnotifier. Here are the configs I use for each:

```python
systray_config = dict(
	icon_size=20,
	padding=16,
	background='#DE8F787F',
	decorations=[
		PowerLineDecoration(path="forward_slash", extrawidth=20)
	],
	name="systray"
)

statusnotifier_config = dict(
	menu_icon_size=24,
	menu_fontsize=24,
	menu_width=400,
	background='#DF5B617F'
)
```
