### ISSUE TITLE
ImgMask not working properly

### ISSUE THREAD

**Issue by ervinpopescu** [elParaguayo/qtile-extras#266]
https://github.com/elParaguayo/qtile-extras/assets/84532402/ca27045e-ca63-4f28-acc4-bb766e41be58

https://github.com/elParaguayo/qtile-extras/assets/84532402/558f66b6-32b7-489d-b3bf-ddb865401866

No errors in log.

```console
$ grep -w '^Version' /usr/lib/python3.11/site-packages/qtile_extras-*.dist-info/METADATA | awk -F":" '{print $2}'
 0.22.2.dev114+ged01fd8
```

**Comment by elParaguayo** [comment]
Have you got decorations on that widget? I can't see any in that config screenshot but it looks like there's a rect decoration around it.

I've just tested that widget on my system and it works fine with no decoration but does break when there is a decoration.

**Comment by elParaguayo** [comment]
Can you try #268 please.

**Comment by ervinpopescu** [comment]
Yes, I have decorations. Sorry, busy day, will give you the updated widget right now.

```py
current_layout_icon = widget.CurrentLayoutIcon(
    padding=13,
    scale=0.8,
    mouse_callbacks={
        "Button2": set_layout_all(),
        "Button3": lazy.spawn("/home/ervin/bin/rofi_layout.py"),
    },
    # use_mask=True,
    foreground=colors["darkblue"],
    decorations=[
        RectDecoration(
            colour=decor_bg,
            radius=20,
            filled=True,
            padding_y=0,
            padding_x=0,
        ),
    ],
)
```

#268 works! Closing this now or will you close it in the PR?

**Comment by elParaguayo** [comment]
It will close with the PR.

Can you confirm it works for your other issue too?
