### ISSUE TITLE
Groupbox decoration issues

### ISSUE THREAD

**Issue by ervinpopescu** [elParaguayo/qtile-extras#267]
Groupbox decoration has unwanted borders around it, only when on the first group. Tried lowering the `fontsize`, adding padding, adding margins. Don't really know the difference between padding and margins yet, sorry! :)

https://github.com/elParaguayo/qtile-extras/assets/84532402/ca27045e-ca63-4f28-acc4-bb766e41be58

widget config:
```py
widget.GroupBox(
    active=colors["darkblue"],
    disable_drag=True,
    font=settings["icon_font"],
    fontsize=settings["font_size"] - 7,
    hide_unused=True,
    inactive=colors["bg3"],
    margin_x=14,
    other_screen_border=colors["turquoise"],
    # padding_x=3,
    # padding_y=3,
    # rounded="true",
    this_current_screen_border=colors["darkblue"],
)
```

**Comment by elParaguayo** [comment]
That's bizarre.

The decoration has no knowledge of the widget's contents and should be drawn identically each time.

**Comment by ervinpopescu** [comment]
My configuration is bizarre maybe :) I really need to tackle some issues with it, but I have no time for that ATM. Once I get on it, maybe I'll check out these issues myself.

**Comment by elParaguayo** [comment]
Unsurprisingly, I can't recreate this one and I'm really struggling to see how it could happen but you may want to see if #268 also fixes this.

**Comment by ervinpopescu** [comment]
Yep, it does fix it. Thanks!
