### ISSUE TITLE
no setup.py in the repo

### ISSUE THREAD

**Issue by mairm1340** [elParaguayo/qtile-extras#279]
Hi
I dont see setup.py file in the repo...

**Comment by elParaguayo** [comment]
Doesn't need one. You can do `pip install .`.

I suspect the docs are out of date!

**Comment by mairm1340** [comment]
I am sorry but can you help me with the complete command so that  I can try..

**Comment by elParaguayo** [comment]
Ok but first you need to tell me what you've done (i.e. cloned repo) and what commands you were trying to run. I can have a guess but you haven't given me enough information yet.

**Comment by mairm1340** [comment]
I m on ubuntu and I want to run qtile.

**Comment by mairm1340** [comment]
i did download the repo on my drive

**Comment by elParaguayo** [comment]
Ok... you want to run qtile? Have you installed qtile already? This is the `qtile-extras` repo which provides additional widgets and decorations but it doesn't install qtile.

**Comment by mairm1340** [comment]
closing this
thank you very much
