### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by kobzar** [elParaguayo/qtile-extras#282]
How to install this pkg manualy?
On the documentation i found 
"Clone this repo and run "
```python
python setup.py install
```
But this repo doesnt contans setup.py file

**Comment by elParaguayo** [comment]
Ah, yes. Need to update the docs!

You can do `pip install --user .` or, with the `build` and `installer` modules do:
```
python -m build --wheel
python -m installer dist/*.whl
```

**Comment by elParaguayo** [comment]
Is this working for you now?

**Comment by kobzar** [comment]
I dont know. This is a worse method for me to install modules. 
So, i jusct copy the battery.py file in my extrax local dir (.config/qtile/eaxtras) impotd and use it. 
All fine.Thanks

**Comment by elParaguayo** [comment]
Yes. I understand about installing extra modules.

I'll try to get this onto pypi with the next release.
