### ISSUE TITLE
[BUG] Decoration not working with Qtile 0.23

### ISSUE THREAD

**Issue by kraanzu** [elParaguayo/qtile-extras#289]
The rect decorations just suddenly stopped working as soon as I updated qtile from 0.22 to 0.23 (ie the decorations doesn't apply)
It was working fine with 0.22 but it now won't

**Comment by elParaguayo** [comment]
What version of qtile-extras are you running?

**Comment by kraanzu** [comment]
> What version of qtile-extras are you running?

From `yay -Q | grep qtile`

```
qtile 0.23.0-1
qtile-extras 0.23.0-1
```

> Are you saying the decoration doesn't show at all? That's odd as I'm running 0.23 and decorations show fine.

Yep :(
That seems odd if it's running fine for you

I'll check into it a bit more. If there's anything I can try, do let me know

**Comment by elParaguayo** [comment]
Can you share your config?

**Comment by kraanzu** [comment]
Well.... Looks like a reboot did the trick.
Not really sure what went wrong haha

I'll close this issue then :)
