### ISSUE TITLE
RectDecoration stopped working

### ISSUE THREAD

**Issue by zordsdavini** [elParaguayo/qtile-extras#292]
Some time ago (two month or more) all my decorations stopped working. Used to draw nice corners.

Ex., with BLUE and BLACK is colour in format '#984735'
```
        widget.Clock(
            format='%Y-%m-%d %H:%M',
            foreground=BLACK,
            decorations=[
                RectDecoration(colour=BLUE, radius=8, filled=True, padding_y=3)
            ]),
```

Using latest git versions of qtile and qtile_extra.

**Comment by elParaguayo** [comment]
Thanks.

Can you give me version info for both packages (e.g. commit numbers) and I'll take a look but I'm not aware of these being broken.

**Comment by zordsdavini** [comment]
Sure :)
qtile-extras-git r292.f2b35c5-1
qtile-git 0.23.0.r48.g8547c215-1

**Comment by zordsdavini** [comment]
@elParaguayo maybe you can describe how should I debug what is wrong? Maybe I have something installed and that broke decorations?

**Comment by elParaguayo** [comment]
Ideally, you'd do a got bisect to find out which commit broke the decoration. However, the current CI test suite should be checking that decorations are rendered correctly.

**Comment by elParaguayo** [comment]
Can you share your config and a screenshot of the issue?

**Comment by zordsdavini** [comment]
Came back to this issue... Tried bisect. Tested till 036b3383c9d394d8de331776ec4b0bcf9dc7a3a0 (later changed something and my config is broken for this). No success. So bisect didn't help. Problem is not qtile codebase. Digging deeper. I have feeling that I added something and broke decorations. Will inform

**Comment by zordsdavini** [comment]
![image](https://github.com/elParaguayo/qtile-extras/assets/4191548/ae42700c-ebff-482e-b574-d349196ced8e)
[config.py.txt](https://github.com/elParaguayo/qtile-extras/files/13809425/config.py.txt)

Added cleared a little bit config and screenshot

**Comment by zordsdavini** [comment]
stupid me... One thing still not clear - how it happened

```
from qtile_extras import widget
```
not from qtile

**Comment by zordsdavini** [comment]
and this happened during auto migration
