### ISSUE TITLE
Colors of the text in the popup of the bluetooth widget not changing

### ISSUE THREAD

**Issue by MagnuSiwy** [elParaguayo/qtile-extras#322]
The borders change their color, same as background. Unfortunately the `highlight_colour`, `menu_foreground` and `menu_foreground_highlighted` don't change the default colors of the menu popup.

![menuPopup](https://github.com/elParaguayo/qtile-extras/assets/84531183/81a2b65c-f4ba-42eb-998e-f7333d7a35bd)

**Comment by elParaguayo** [comment]
Thanks for the report. I'll take a look when I can.

**Comment by elParaguayo** [comment]
Can you see if #324 fixes this for you.

**Comment by MagnuSiwy** [comment]
I'm using qtile-extras-git from AUR 0.24.0.r325

If I understand how it works correctly, I'm on 325 and it still doesn't work unfortunately

**Comment by elParaguayo** [comment]
It's not merged so that wouldn't work. You'd need to build from the branch with these changes to test it.

**Comment by elParaguayo** [comment]
OK. I've merged this.

**Comment by MagnuSiwy** [comment]
Ok, thank you very much. I tried installing the thing, but I installed stuff from the main branch by mistake. Great it works now and sorry for my unavailability
