### ISSUE TITLE
ALSAWidget bar not visible

### ISSUE THREAD

**Issue by ACosmicWolf** [elParaguayo/qtile-extras#33]
![image](https://user-images.githubusercontent.com/95919584/149331645-17d3663c-184f-4a5a-9cc4-d64aa7d56198.png)

ALSAWidget config
```
widget.ALSAWidget(
  mode="both",
  theme_path="/usr/share/icons/Paper/24x24/panel",
  background=colors[14],
),

**Comment by elParaguayo** [comment]
Sorry. It's not clear what I'm meant to be looking at here.

When the mode is "both" you get the icon on your bar all of the time (I assume that volume icon is from this widget) and, when you change the volume, you'll see the bar.

Is that not what you're seeing or what you want?

**Comment by elParaguayo** [comment]
Also, I should add, that bar looks really nice!

**Comment by ACosmicWolf** [comment]
I am not able to see the bar when i change the volume. 
i have imported qtile extras like `from qtile_extras import widget`

**Comment by elParaguayo** [comment]
OK. Anything in your log?

What happens when you run `amixer get Master` from a terminal?

**Comment by ACosmicWolf** [comment]
Nothing in the log.

Output of amixer get Master
```
~ ❯ amixer get Master                                                             5m 16s
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 59 [68%] [-21.00dB] [on]

**Comment by elParaguayo** [comment]
ok. Try this:
```
qtile cmd-obj -o widget alsawidget -f eval -a self.volume
```

**Comment by ACosmicWolf** [comment]
The bar still doesnt appear :( 

Output of the command.
```~ ❯ qtile cmd-obj -o widget alsawidget -f eval -a self.volume
(True, '-1')

**Comment by elParaguayo** [comment]
Thanks - this is just showing what the widget thinks is the current volume.

The issue is the regular expression is not matching anything with that output. I'll need to submit a fix.

**Comment by elParaguayo** [comment]
If you do `qtile cmd-obj -o widget alsawidget -f eval -a "self.status_change(50,False)"` you should hopefully see the bar - (it's not a fix though).

**Comment by ACosmicWolf** [comment]
Oh sorry forgot it wasnt a fix.
I will try to solve it if I can.

**Comment by elParaguayo** [comment]
I've submitted a fix. If the tests pass then I'll merge this.

**Comment by ACosmicWolf** [comment]
oh ok.
Thank You Very Much.
