### ISSUE TITLE
Interactive network widget with NetworkManager

### ISSUE THREAD

**Issue by researcher2312** [elParaguayo/qtile-extras#343]
I think that NetworkManager is more popular than IWD, is there a possibility to implement the communication with the Network Manager via dbus on the network widget? If this is not in the works, I can work on it and submit a pull request.

**Comment by elParaguayo** [comment]
I won't be working on it as I don't use NetworkManager. You're welcome to work on one but I'm slightly reluctant to merge anything into this repo that I can't test locally. Not to say I won't, but that's not how this repo has worked so far.
