### ISSUE TITLE
[enhancement] adding popup toolkit config to the doc

### ISSUE THREAD

**Issue by nizaralheet** [elParaguayo/qtile-extras#371]
Hi ,
i was trying to change a popup drawing place , but i couldn't find any thing about how i should do it at the docs .
i manged to understand i have to add the keys like this popup.show ('x=','y=') after looking at the source code at
>[toolkit.py](https://github.com/elParaguayo/qtile-extras/blob/main/qtile_extras/popup/toolkit.py#L219)
```python
     def show(
        self,
        x: int | float = 0,
        y: int | float = 0,
        centered: bool = False,
        warp_pointer: bool = False,
        relative_to: int = 1,
        relative_to_bar: bool = False,
        qtile: Qtile | None = None,
        hide_on_timeout: int | float | None = None,
```

Because i can't see that at the docs i didn't know what exactly was the key i should add and the ,so adding this actually would be great .
Ans thank for maintaining the repo

**Comment by elParaguayo** [comment]
Yup - great suggestion. #372 will fix this.
https://qtile-extras--372.org.readthedocs.build/en/372/manual/ref/popup.html
