### ISSUE TITLE
multiple highlight methods on popup toolkits

### ISSUE THREAD

**Issue by nizaralheet** [elParaguayo/qtile-extras#375]
Hi , i was trying to make a popup list for the power profiles .

![image](https://github.com/user-attachments/assets/d580c774-c993-4e6e-8130-f4f08aaaba6f)

so i used an images (svg icons) on the popup ,i was trying to have some thing like this but with images instead of text 

![image](https://github.com/user-attachments/assets/6babb1d3-ab7e-43d5-aa22-769aad6d5573)
so i made a dark version of the icons then realized that i can't use two types of the highlighting -block highlight and a dark icon image highlight  , so is there a way to use two types on the same widget ? i have tried to stack a transparent or empty widget with block highlight on the same spot but didn't work as i expected .

There is a another thing about highlighting that i want ask  ,it is not that important but is there  a way to highlight more than one  widget at the same time like in the app list i could only highlight the icon or the text but not both .

**Comment by elParaguayo** [comment]
The issue is a fair one. I've just not had time to look at it, nor is it a priority for me. 

I'd happily look at a PR if you wanted to have a go at fixing it.
