### ISSUE TITLE
Vertical Groupbox2 Widget, problems with blocks.

### ISSUE THREAD

**Issue by Sinaaaa** [elParaguayo/qtile-extras#394]
I copied the following rules from the documentation:
```
                rules = [
    GroupBoxRule(block_colour="ec2997").when(screen=GroupBoxRule.SCREEN_THIS),
    GroupBoxRule(block_colour="ece629").when(occupied=True), 
    GroupBoxRule(text_colour="8a8ea5")
			    ],
```

My expectation is that one active group would be marked purple & and the not empty groups would be marked with yellow. 

This is very much not working as seen here:
![screenshot_2024111310:5901](https://github.com/user-attachments/assets/319c7b12-7341-4eca-aced-a28802e0fdf0)
Though the color behavior seems rather random at first glance.

It's worth noting that if I replace "block" with "line" in the code it works perfectly, well so far :-)

-------------------

Furthermore the blocks are not centered properly and reacting oddly to changes in padding, padding=0 looks especially weird, but this may not necessarily be a bug, since I have not digested the documentation properly yet.
![screenshot_2024111311:1409](https://github.com/user-attachments/assets/d2a1bc3a-a43a-4a09-8abf-b83edf88c5af)

**Comment by Sinaaaa** [comment]
Using the following settings the box dimensions have been tamed:
```            
                padding=2,
                margin_x=-10,
                margin_y=-1,
```
![screenshot_2024111312:0350](https://github.com/user-attachments/assets/156131ce-c1b7-4a53-a3e1-5ccb45530d5e)

**Comment by elParaguayo** [comment]
That shouldn't be necessary. I'll fix the blocks!

**Comment by elParaguayo** [comment]
I've pushed a commit to the PR that should fix the blocks.

**Comment by Sinaaaa** [comment]
> I've pushed a commit to the PR that should fix the blocks.

Thank You, I'll test it tomorrow.
