### ISSUE TITLE
Vertical Groupbox2 Widget, odd behavior with Termite terminal.

### ISSUE THREAD

**Issue by Sinaaaa** [elParaguayo/qtile-extras#396]
```          
      rules = [ 
    GroupBoxRule(line_colour="C1C9EB").when(focused=True),      
    GroupBoxRule(text_colour="C1C9EB").when(focused=True),     
    GroupBoxRule(text_colour="07e8f0").when(func=has_discord),                   
    GroupBoxRule(text_colour="ba918b").when(focused=False, occupied=True),
    GroupBoxRule(text_colour="8a8ea5").when(focused=False, occupied=False), 
    GroupBoxRule(line_position= GroupBoxRule.LINE_TOP | GroupBoxRule.LINE_BOTTOM,),
    GroupBoxRule(line_width=2),
                            ],
```

When I'm on an empty group & I start the terminal emulator `Termite`, then the group indicator and lines for this active group disappear. I tried like 20 other apps & this does not occur with them.

My suspicion is that qtile might find it strange that termite only displays a ~ as its title when starting. 

This is from xprop:

```
WM_ICON_NAME(STRING) = "~"
_NET_WM_ICON_NAME(UTF8_STRING) = "~"
WM_NAME(STRING) = "~"
_NET_WM_NAME(UTF8_STRING) = "~"

```
![screenshot_2024111317:0507](https://github.com/user-attachments/assets/2bc711d0-dac7-4d17-a22f-c24f1357da11)
^ I'm on group3, discord is making g6 glowy.

**Comment by elParaguayo** [comment]
That's very weird. The widget does not care about window names. Are there any messages in your log?

**Comment by elParaguayo** [comment]
The error seems to be in your hasdisxord function. 

It looks like the window name is not immediately set and so is `None`.  This means looking for the string `Discord` inside the name will give an error. You can fix this by checking if the name is `None` before checking for the discord string.

**Comment by Sinaaaa** [comment]
You are right, disabling that really fixes it.

Though I'm not sure if I understand how to proceed.
```
def has_vlc(rule, box):
    for win in box.group.windows:
        if "VLC" in win.name:
            return True

    return False
```

I copied this from the documentation & changed vlc to discord.

```
def has_vlc(rule, box):
    for win in box.group.windows:
        if "none" in win.name:
            return False
        elif "VLC" in win.name:
            return True
    return False
```
It shouldn't be this, confused dumb face mode on.

**Comment by elParaguayo** [comment]
```python
def has_vlc(rule, box):
    for win in box.group.windows:
        if win.name is not None and "VLC" in win.name:
            return True
    return False
```

**Comment by Sinaaaa** [comment]
Thanks, you are the best, it's working now!
