### ISSUE TITLE
PulseVolume not updating volume %

### ISSUE THREAD

**Issue by spslabo** [elParaguayo/qtile-extras#399]
Hello,
The PulseVolume widget doesn't seem to be able to update the volume % anymore and is stuck at 0%.
Looking at the logs I can see the below error
`WARNING libqtile pulse_volume.py:get_sink_info():L116 Could not get info for default sink`
The volume control actually works though, I can use my scrollwheel to change the volume.
Using `qtile-extras 0.29.0-1` from the AUR
Current config:
```python
              widget.PulseVolume(
                    fmt="  {}",
                    padding = 3,
                    mouse_callbacks={'Button1': lazy.group['scratchpad'].dropdown_toggle('pavucontrol')}
                    ),
```

**Comment by elParaguayo** [comment]
This may not be a qtile-extras issue as it's based on the `PulseVolume` widget in qtile. Can you see if that widget works ok?

However, we are dependent on a third-party library to access the pulse server so the issue may be further upstream.

**Comment by spslabo** [comment]
Hello @elParaguayo ,
I was able to re-create the issue, it happens when the qtile config is reloaded. I don't have to make any changes to it, just press Mod + r and the percentage on the widget will go to 0% and not change.
Do you want me to create this issue on the main qtile github and close it here? Thanks

**Comment by spslabo** [comment]
Thanks, created https://github.com/qtile/qtile/issues/5111.
