### ISSUE TITLE
decorations control

### ISSUE THREAD

**Issue by mosaleh52** [elParaguayo/qtile-extras#42]
awesome work , thanks for this great stuff 
i have some questions 
- can i control decorations color from my widget or qtile config i have a custom taskwarrior widget and i want to change decoration colors for the widget is this possible
- can i do change bar color with widget to 
- can i use decorations by putting it's files on the same folder without installing the whole package 
thanks in advance ;)

**Comment by elParaguayo** [comment]
> awesome work , thanks for this great stuff i have some questions
> 
> * can i control decorations color from my widget or qtile config i have a custom taskwarrior widget and i want to change decoration colors for the widget is this possible

Ideally, if you want to change them, you need to change your config file and reload it.

You probably could change it via code but it could be pretty messy. Never tried it!

> * can i do change bar color with widget to

Same as above. Ideally, you would change your bar colour in the config and reload the config.

That said, you could change the bar's `background` property and force a redraw of the bar.

In a widget, you could do
``` python
self.bar.background = new_background_colour
self.bar.draw()
```

> * can i use decorations by putting it's files on the same folder without installing the whole package

Do you mean, can you use decorations without installing qtile-extras? Yes, but I wouldn't recommend it. qtile-extras makes it really easy to add decorations to any widget.

**Comment by mosaleh52** [comment]
> 
>>  Ideally, if you want to change them, you need to change your config file and reload it.
> > You probably could change it via code but it could be pretty messy. Never tried it!
> > 
> is this even posibel with custom widgets to control backgrournd property without reloading
>>  That said, you could change the bar's `background` property and force a redraw of the bar.
> > 
> > In a widget, you could do
> > 
> > ```python
> > self.bar.background = new_background_colour
> > self.bar.draw()
> > ```
> this is a great idea i will try it , thanks

**Comment by elParaguayo** [comment]
> > Ideally, if you want to change them, you need to change your config file and reload it.
> > You probably could change it via code but it could be pretty messy. Never tried it!
> 
> Is this even possible with custom widgets to control background property without reloading

I've actually just pushed a new update to `RectDecoration` where you can add a `use_widget_background=True` argument when configuring the decoration. You can then set the decoration's colour by setting the widget's background colour. Any part of the widget that is not covered by the decoration will be coloured with the bar's background colour.

Does that help?

**Comment by mosaleh52** [comment]
> > > Ideally, if you want to change them, you need to change your config file and reload it.
> > > You probably could change it via code but it could be pretty messy. Never tried it!
> > 
> > 
> > Is this even possible with custom widgets to control background property without reloading
> 
> I've actually just pushed a new update to `RectDecoration` where you can add a `use_widget_background=True` argument when configuring the decoration. You can then set the decoration's colour by setting the widget's background colour. Any part of the widget that is not covered by the decoration will be coloured with the bar's background colour.
> 
> Does that help?

Yes this will make the task easier, now I am only dealing with widget background color I will try to find a workaround for this part by hacking on source code and hope it will work 
https://github.com/mosaleh52/dot_files/blob/master/.config/qtile/widgets.py
here is my widget named time warrior your suggestions are welcome, my goal is to use background color instead of font color

**Comment by elParaguayo** [comment]
If you have general questions on how to make widgets for qtile (and which aren't questions about my decorations) then feel free to post these on the main qtile github page.
