### ISSUE TITLE
[Popup toolkit] send a popup to a specific screen.

### ISSUE THREAD

**Issue by a2n-s** [elParaguayo/qtile-extras#50]
I would like to show a popup only on the focused monitor, but by default it shows up on the main monitor, which, as it is still related to my group-popup-when-changing-group issue on `qtile`, it does not make sense to have all these popups on an unfocused monitor :thinking: 

this is what i have right now
```
def text_popup(qtile, text, size=150):
    """
        Opens a popup with a single string of text.
    """
    controls = [
        PopupText(
            font=FONT,
            fontsize=size,
            text=text,
           # other options
        ),
    ]

    layout = PopupGridLayout(
        qtile,
        # other options
    )

    # isolate screen and group on that screen, e.g. group dev on screen 1
    # this works fine
    s = qtile.current_screen.index
    g = qtile.screens[s].group.name

    # show the layout, but only on main monitor (0) by default
    layout.show(centered=True)

    qtile.call_later(.5, layout.kill)  # kill popup after 1 second
```

maybe add something like `qtile.<window>.togroup(g)`
it seems the `layout.show` does not give the window id, nor its name, i have also seen the `qtile.windows_map` field that list all window ids, but i do not know how to access the right popup window name or id...

**Comment by elParaguayo** [comment]
Nice idea. Will look into it.

**Comment by elParaguayo** [comment]
#53 should fix this.

**Comment by a2n-s** [comment]
it is a bit confusing, because my HDMI cable appears to not work any more...
it was already dodgy but now it does not respond at all

cannot test the feature right now, really disappointed...

however I updated `qtile-extras-git` through `paru`,
double checked the source code and your commit is there and does not break anything

so at least I know it still works on a single monitor setup :ok_hand:

**Comment by elParaguayo** [comment]
Sorry to hear that. I'm pretty confident the fix will work as, previously, I hadn't included any code to adjust for the fact that there may be more than one monitor!

Once you get your screen working, if you still have issues, just let me know.

**Comment by a2n-s** [comment]
do not worry, this is just the cable, the monitor and the laptop are working just fine! :ok_hand: 

and i managed to connect the monitor, and it works indeed, just as expected!
well done man :clap: :clap: :yum:
