### ISSUE TITLE
Grouping two widgets in a single RectDecoration

### ISSUE THREAD

**Issue by biscuitrescue** [elParaguayo/qtile-extras#61]
i was wondering if it would be possible to group to separate widgets in the same rectdecoration. i wanted to have the battery widget and the upower widget in the same deoration.
![image](https://user-images.githubusercontent.com/67876678/170831931-c6b628ae-f80b-4fb5-ab17-721f43c6b093.png)

**Comment by elParaguayo** [comment]
Yes, it's possible.

I answered a similar question on reddit recently: https://www.reddit.com/r/qtile/comments/uupil3/can_rectdecoration_from_qtileextra_include_two/

**Comment by elParaguayo** [comment]
Can we close this now or are you still having issues?

**Comment by biscuitrescue** [comment]
yes my issue has been resolved thank you
