### ISSUE TITLE
AttributeError when using GlobalMenu()

### ISSUE THREAD

**Issue by Javigo07** [elParaguayo/qtile-extras#62]
Whenever I try to use GlobalMenu, I don't get any response when reloading config. The module is correctly imported since I'm using ALSAWidget as well and it works fine. The logs only show a configuration error, but my configuration of that widget is only `GlobalMenu(),`.

I use `qtile cmd-obj -o cmd -f reload_config` but it doesn´t show any output. 
logs: https://dpaste.com/67YXMXXZW  
qtile check log: https://dpaste.com/HJBHSC7L3

When I execute de config.py as a Python program it shows the following output:
` ❯ python .config/qtile/config.py | wgetpaste
Traceback (most recent call last):
  File "/home/javigo07/.config/qtile/config.py", line 1, in <module>
    from modules import *
  File "/home/javigo07/.config/qtile/modules/__init__.py", line 4, in <module>
    from modules.screens import screens, layouts, floating_layout
  File "/home/javigo07/.config/qtile/modules/screens.py", line 94, in <module>
    widget.GlobalMenu(),
  File "/usr/lib/python3.10/site-packages/qtile_extras/widget/__init__.py", line 104, in __getattr__
    raise AttributeError
AttributeError `

Following the path, it shows me this section of code:
` 102     def __getattr__(name):
103         if name not in registry:
104             raise AttributeError
105 
106         if name in widgets:
107             package = "qtile_extras.widget"
108         else:
109             package = "libqtile.widget"
110 
111         module_path = f"{package}.{registry[name]}"
112 
113         return import_class(module_path, name, fallback=fallback) `

**Comment by elParaguayo** [comment]
Have you got the latest qtile-extras installed?

**Comment by Javigo07** [comment]
I have latest qtile-extras-git from AUR. Already deleted and reinstalled, just in case, but no luck yet.

**Comment by elParaguayo** [comment]
Can you just open a python terminal and try:
```
>>> from qtile_extras import widget
>>> gm = widget.GlobalMenu()
```
Let me know what happens.

**Comment by Javigo07** [comment]
Hereś my config file: https://github.com/Javigo07/.config/tree/main/qtile/qtile The working-screens.py is an old backup.
Also, the output gave me that GlobalMenu() does exist.

**Comment by elParaguayo** [comment]
Weird. I don't get any issues when I run `python config.py` (other than me needing to hardcode some colours).

**Comment by elParaguayo** [comment]
Have you restarted qtile since updating qtile-extras?

**Comment by Javigo07** [comment]
Deleted old pacman and yay cache, reinstalled qtile-extras and restarted qtile and now I am able to restart/reload_config from qtile commands, but the GlobalMenu() is not showing. Tried with VLC as the Docs show, but Menu still showing on the app.
![image](https://user-images.githubusercontent.com/37010420/170835857-8baf3181-a8b7-46cb-b7ce-745ab1116bd5.png)

qtile check now is showing the following output: https://dpaste.com/8FYNY9HYC

**Comment by elParaguayo** [comment]
You can ignore that message.

Can you check your log and see if there are any messages.

**Comment by Javigo07** [comment]
https://dpaste.com/3WLBL54WV Well, I don't see anything new, weird or bad. It looks fine.

**Comment by elParaguayo** [comment]
Your log is flooded with dbus error messages. It won't work if dbus isn't working properly.

How are you starting qtile?

Is dbus running? What happens if you install `d-feet` and try running that?

**Comment by Javigo07** [comment]
What should I see for? 
The app opens and shows data for blueman, bluez, mpris2 for Firefox, keepass, those things.

**Comment by elParaguayo** [comment]
Interesting - so dbus is running.

In the session bus, search for "registrar".

**Comment by Javigo07** [comment]
It doesn't appear.

**Comment by Javigo07** [comment]
Btw, on the log it appears something about registrar.py:  
` WARNING libqtile registrar.py:start():L64 Starting Registrar: self.started=False `
Could this be related?

**Comment by elParaguayo** [comment]
That's an old log message that I need to remove.

However, you see that line about starting the registrar and immediately after is a dbus error message.

So, the issue seems to be your dbus installation, not the widget. 

What happens when you do `cat /var/lib/dbus/machine-id`?

**Comment by elParaguayo** [comment]
Also `cat /etc/machine-id`

**Comment by Javigo07** [comment]
I got `6a09bc4e3440881536581c5c6202e9fa` with `cat /etc/machine-id`, but as the log states, `cat /var/lib/dbus/machine-id` doesn´t exist (No such file or directory).

**Comment by elParaguayo** [comment]
ok so I don't know why it's missing but you could do `sudo ln -s /etc/machine-id /var/lib/dbus/machine-id`.

After that, restart qtile.

**Comment by Javigo07** [comment]
Alright, now it shows for some apps (Telegram-Desktop, KeePassXC, VLC). Others like Firefox don't show anything (but I guess that's because Firefox doesn't send the menu through dbus as VLC, according to the GlobalMenu() docs you wrote). 

In fact, solving this also fixed my Mpris2 widget that didn't work before that. Thank you so much.

**Comment by elParaguayo** [comment]
Yeah - it only works for apps that have implemented the spec.

Glad it's working.
