### ISSUE TITLE
Add an IP widget.

### ISSUE THREAD

**Issue by a2n-s** [elParaguayo/qtile-extras#63]
**What I wanted to do**
I wanted to add a widget in my `qtile` bar, next to the networking ones, to display the IP address of my machine.

**The problem I encountered**
However, I did not find any such widget in neither the code base of `qtile` nor the code base of `qtile-extras`... I looked at the `Net` and `Wlan` widgets, but did not find any format option called `ip`: there are `interface`, `up`, `down` and `total` in the `Net` widget, and `essid`, `quality` and `percent` in the `Wlan` widget.
Am I missing the widget, does it exist in the first place? :open_mouth: 

**Enhancement**
If it does not, would you be okey to add one to the repo? Most likely in `qtile-extras`, I think.
I would be more than happy to help you in a PR if you accept others to contribute :wink:

**First draft**
```
import subprocess
from libqtile import widget


class IP(widget.base.ThreadPoolText):
    """A simple widget to display the IP address of the system."""
    defaults = [
        ("update_interval", 3600, "Update interval for the IP widget"),
        (
            "format", "IP {address}", "IP address display format",
        ),
    ]

    def __init__(self, **config):
        super().__init__("", **config)
        self.add_defaults(IP.defaults)

    def poll(self):
        variables = dict()

        address = subprocess.check_output(["dig", "+short", "myip.opendns.com", "@resolver1.opendns.com"])
        variables["address"] = str(address).strip()
       
        return self.format.format(**variables)
```
according to [this article](https://www.makeuseof.com/get-public-ip-address-in-linux/). There are many ways to get one's public IP address on a linux machine, `dig` appears to be quite common.

I am not sure about the exact formating you want there, this can be adapted of course, and any detail should be discussed :yum:

**Comment by elParaguayo** [comment]
You don't need a new widget for this. Just use the `GenPollUrl` widget e.g.
``` python
widget.GenPollUrl(url="https://api.ipify.org?format=json", parse=lambda x: f"IP: {x['json']}")
```

**Comment by a2n-s** [comment]
oooh that is smart!

let me check the solution :+1:

**Comment by elParaguayo** [comment]
Sorry - typo in my example. Should be:
``` python
widget.GenPollUrl(url="https://api.ipify.org?format=json", parse=lambda x: f"IP: {x['ip']}")
```

**Comment by a2n-s** [comment]
> ```python
> widget.GenPollUrl(url="https://api.ipify.org?format=json", parse=lambda x: f"IP: {x['ip']}")
> ```

Thanks a lot, it works just fine for me :ok_hand:

I close the issue with that solution :+1:
