### ISSUE TITLE
[Feature Request] Package for Nix/NixOS

### ISSUE THREAD

**Issue by jhilker1** [elParaguayo/qtile-extras#67]
Hey there,

Thanks for creating this package; I've enjoyed being able to use it in my personal config.

I've been getting ready to switch to NixOS but haven't been able to install this properly unless I completely rebuild qtile with the package. Would it be possible for you to package this for Nix and NixOS?

**Comment by elParaguayo** [comment]
I don't use NixOS so I wouldn't know where to begin with packaging. I can ask on the r/qtile reddit forum to see if anyone can help.

**Comment by jhilker1** [comment]
Completely fine, thanks so much! I'm brand new to NixOS so my method probably isn't great, I'll ask on r/NixOS as well.
