### ISSUE TITLE
GlobalMenu mouse clicks not working

### ISSUE THREAD

**Issue by skela** [elParaguayo/qtile-extras#77]
So i've been using the global_menu branch of yours for a while, but after noticing its now merged into main, i gave main a go.

The only problem was the menu no longer registers mouse clicks.
The only real difference I could see in code between my global_menu branch checkout, and main, was a tiny addition added to toolkit.py line 107

In main the code is like this:

`self.keys = {k: [keysyms[key.lower()] for key in v] for k, v in self.keymap.items()}`

but in the checkout

`self.keys = {k: [keysyms[key] for key in v] for k, v in self.keymap.items()}`

i tried to remove the .lower call in main, and the menu started working again with mouseclicks.
So might be some scenarios where key.lower() fails, or something like that?

**Comment by skela** [comment]
The program I noticed the menu not working in was vs code. (in case it depends on the contents of the menu or something like that)

**Comment by skela** [comment]
(Also side note, and forgive for asking it here, but do you have any tips or guides on how to get into qtile debug, im kinda forced to making changes and reloading, but would be so cool if i could attach a debugger or something) :D

**Comment by elParaguayo** [comment]
The `.lower` change is to make the widget compatible with the main qtile branch. `qtile-extras` (currently) requires you to be running the latest git version of qtile, not the releases.

**Comment by elParaguayo** [comment]
> (Also side note, and forgive for asking it here, but do you have any tips or guides on how to get into qtile debug, im kinda forced to making changes and reloading, but would be so cool if i could attach a debugger or something) :D

You've got a few options here:
1) Se logging to debug level and look at the logs (`qtile cmd-obj -o cmd -f debug`). This relies on the debug logging messages already in the code so may or may not be useful (`qtile cmd-obj -o cmd -f warning` to return to default warning level).
2) Use the `eval` command for command objects. You can inspect objects' properties etc. with commands like `qtile cmd-obj -o cmd -f eval -a "self.windows_map"` etc.
3) Use `pdb` - this is available by running `qtile cmd-obj -o cmd -f pause`.

**Comment by skela** [comment]
Im running qtile version 0.21.0 , i guess, perhaps an idea would be to tag qtile-extras with the qtile versions, that way people can perhaps match them up easier. although i suppose the global menu stuff came much later than the release of 0.21.0, so maybe no point.

ok thx, then its not a bug, sorry for the noise :P

**Comment by elParaguayo** [comment]
I'll be doing tagged version releases from the next qtile release onwards so these issues won't happen again.
