### ISSUE TITLE
Missing Dependencies in `PKGBUILD`, for clean chroot build

### ISSUE THREAD

**Issue by Ruturajn** [elParaguayo/qtile-extras#78]
Hi,
I was trying to add `qtile-extras` to a custom Arch ISO, that I am making, by creating a custom local repository. While doing this I tried to build `qtile-extras` in `clean chroot`, and the build failed due to these missing dependencies: `"git" "python-setuptools" "python-wheel" "python-pip"`. So, I thought that I should let you know. Let me know if I should open a pull request, or if you think it's just a minor change, you can do it yourself.

Thanks

**Comment by elParaguayo** [comment]
Thanks for the comments.

`git` and `python-setuptools` (actually `python-setuptools-scm`) should be `makedepends`. Why are `python-wheel` and `python-pip` needed?

As for the PKGBUILD, I should remove it from the repo as the relevant one is in the AUR (https://aur.archlinux.org/packages/qtile-extras-git) - but this one should still have the right dependencies added.

**Comment by Ruturajn** [comment]
Ohh, Ok, sure.

Thank you

**Comment by elParaguayo** [comment]
Added these dependencies to the PKGBUILD.

**Comment by Ruturajn** [comment]
Thank You 👍
