### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by cr1ogen** [elParaguayo/qtile-extras#8]
Is not a bug, but i have a question. How import qtile-extras to config.py? Nice Work!!

**Comment by elParaguayo** [comment]
Thanks!

Once you've installed `qtile-extras`, you can just do something like:
``` python
from qtile_extras import widget as extrawidgets

# widgets can then be added to your bar by doing
extrawidgets.UPowerWidget(),
extraswidgets.WiFiIcon(),
# etc.
```

**Comment by cr1ogen** [comment]
It works,Thank you!!
