### ISSUE TITLE
Cannot create `_PopupLayout` instances in X11

### ISSUE THREAD

**Issue by ajoino** [elParaguayo/qtile-extras#95]
I was going to experiment with popups but found that I couldn't create any.
Looking through the logs I found that it crashed on [line 107 of qtile_extras/popup/toolkit](https://github.com/elParaguayo/qtile-extras/blob/159eb19b9e796b7b685c8806c40cca709ed25f59/qtile_extras/popup/toolkit.py#L107), doing something with the keyboard mapping.
It seems the error here is the call to `key.lower()`, which turns the valid key `'Left'` into an invalid key `'left'` (I confirmed in a Python shell that my `libqtile.backend.x11.xkeysyms.keysyms` does not contain `'left'`). 
To solve the issue I monkeypatched `_PopupLayout.defaults` to set `'keymap'` to an empty dict, which allowed the class to be created.

Could anyone confirm this?

**Comment by elParaguayo** [comment]
You need the latest git version of qtile.

**Comment by elParaguayo** [comment]
Once we hit the next release of qtile, I'll do tagged versions of qtile-extras but, for now, qtile-extras assumes you're running the latest git version.

**Comment by ajoino** [comment]
Thanks for the answer!

However, think I borked my python environments, after 5 years of abuse. Luckily I'm not using this machine for a lot longer, then I can start from a clean slate and (hopefully) manage my environments better.
